import { registerStrings } from '../../core/i18n';

/**
 * Strings of the timeline chapter (namespace `timeline`). German first (de-CH: «ss», ’ as thousands separator),
 * then English. Tone: sober, precise, enthusiastic – short sentences, real numbers.
 */
registerStrings('timeline', {
  kicker: 'Kapitel 6 · KOSMOS',
  introHint: 'Zeitachse ziehen oder scrollen · ← → springt zu Ereignissen · Leertaste spielt ab',

  // stat tiles
  sinceBB: 'nach dem Urknall',
  beforeToday: 'vor heute',
  fromNow: 'in der Zukunft',
  todayBig: 'Heute',
  todaySub: '13,8 Mrd. Jahre nach dem Urknall',
  calendar: 'Kosmischer Kalender',
  calendarSub: '1 Jahr = 13,8 Mrd. Jahre',
  calendarYear2: 'im 2. kosmischen Jahr',
  calendarNone: 'jenseits des Kalenders',
  calendarMidnight: 'Mitternacht',
  temp: 'Temperatur des Universums',
  tempSub: 'Strahlung, T ∝ 1/a',
  tempNone: 'vor der Inflation: unbekannt',
  tempCold: 'praktisch absoluter Nullpunkt',
  size: 'Radius des heute sichtbaren Universums',
  sizeSub: 'damals · heute 46,5 Mrd. Lj',
  sizeNone: 'nicht definiert',
  src: 'Modell: T ∝ 1/a mit a ∝ t^½ (Strahlungsära) und t^⅔ (Materieära), Anker 2,725 K heute (COBE/FIRAS) und 3’000 K bei der Rekombination; Alter 13,8 Mrd. Jahre (Planck 2018)',

  // axis
  past: 'Vergangenheit',
  today: 'Heute',
  future: 'Zukunft',
  axisSrc: 'Achse logarithmisch: links Zeit seit dem Urknall bzw. vor heute, rechts Jahre ab heute · Ereignis anklicken zum Springen',
  play: 'Abspielen (Leertaste)',
  pause: 'Pause (Leertaste)',
  prev: 'Vorheriges Ereignis (←)',
  next: 'Nächstes Ereignis (→)',
  events: 'Ereignisse',
  close: 'Schliessen',
  hypothesis: 'Hypothese / Modell',
  source: 'Quelle',
  when: 'Zeitpunkt',
  playing: 'Abspielen … hält bei jedem Ereignis kurz an',

  // eras
  'era.plasma': 'Heisses Plasma',
  'era.dark': 'Dunkles Zeitalter',
  'era.dawn': 'Kosmische Dämmerung',
  'era.galaxies': 'Galaxien-Ära',
  'era.solar': 'Sonnensystem',
  'era.life': 'Leben auf der Erde',
  'era.human': 'Menschheit',
  'era.present': 'Gegenwart',
  'era.near': 'Nahe Zukunft',
  'era.collision': 'Galaxien-Kollision',
  'era.sunend': 'Ende der Sonne',
  'era.stelliferous': 'Ende der Sterne',
  'era.degenerate': 'Ära der Degeneration',
  'era.blackhole': 'Ära der Schwarzen Löcher',
  'era.dead': 'Wärmetod',

  // axis labels (units)
  yr: 'J.',
  agoShort: 'vor {v}',
  inShort: 'in {v}',
}, {
  kicker: 'Chapter 6 · KOSMOS',
  introHint: 'Drag or scroll the time axis · ← → jumps between events · Space plays',

  sinceBB: 'after the Big Bang',
  beforeToday: 'before today',
  fromNow: 'from now',
  todayBig: 'Today',
  todaySub: '13.8 billion years after the Big Bang',
  calendar: 'Cosmic calendar',
  calendarSub: '1 year = 13.8 billion years',
  calendarYear2: 'in the 2nd cosmic year',
  calendarNone: 'beyond the calendar',
  calendarMidnight: 'midnight',
  temp: 'Temperature of the universe',
  tempSub: 'radiation, T ∝ 1/a',
  tempNone: 'before inflation: unknown',
  tempCold: 'practically absolute zero',
  size: 'Radius of today’s observable universe',
  sizeSub: 'back then · today 46.5 billion ly',
  sizeNone: 'not defined',
  src: 'Model: T ∝ 1/a with a ∝ t^½ (radiation era) and t^⅔ (matter era), anchored at 2.725 K today (COBE/FIRAS) and 3,000 K at recombination; age 13.8 billion years (Planck 2018)',

  past: 'Past',
  today: 'Today',
  future: 'Future',
  axisSrc: 'Logarithmic axis: left time since the Big Bang or before today, right years from now · click an event to jump',
  play: 'Play (space)',
  pause: 'Pause (space)',
  prev: 'Previous event (←)',
  next: 'Next event (→)',
  events: 'Events',
  close: 'Close',
  hypothesis: 'Hypothesis / model',
  source: 'Source',
  when: 'When',
  playing: 'Playing … pauses briefly at every event',

  'era.plasma': 'Hot plasma',
  'era.dark': 'Dark Ages',
  'era.dawn': 'Cosmic dawn',
  'era.galaxies': 'Galaxy era',
  'era.solar': 'Solar system',
  'era.life': 'Life on Earth',
  'era.human': 'Humankind',
  'era.present': 'Present',
  'era.near': 'Near future',
  'era.collision': 'Galaxy collision',
  'era.sunend': 'Death of the Sun',
  'era.stelliferous': 'End of the stars',
  'era.degenerate': 'Degenerate Era',
  'era.blackhole': 'Black Hole Era',
  'era.dead': 'Heat death',

  yr: 'yr',
  agoShort: '{v} ago',
  inShort: 'in {v}',
});
