import { registerStrings } from '../../core/i18n';

registerStrings('live', {
  kicker: 'Kapitel 8 · KOSMOS',
  hint: 'Ziehen zum Drehen · Scrollen für mehr · Antippen für Details',
  live: 'Live',
  heroSub: 'Die Internationale Raumstation, jetzt gerade: 400 km hoch, 28’000 km/h schnell. Darunter: wer im All ist, was startet, wie die Sonne bläst.',
  whereAmI: 'Wo bin ich?',
  centerIss: 'ISS zentrieren',
  followIss: 'ISS folgen',
  scrollDown: 'Mehr Live-Daten',
  'stat.alt': 'Höhe · km',
  'stat.speed': 'Tempo · km/h',
  'stat.pos': 'Position',
  'stat.daynight': 'Tag / Nacht',
  'stat.orbits': 'Umläufe seit 1998',
  'stat.people': 'Menschen im All',
  day: 'Tag',
  night: 'Nacht',
  sunlit: 'in der Sonne',
  eclipsed: 'im Erdschatten',
  approx: 'ca. · 15,5 pro Tag',
  aboard: 'an Bord von ISS & Tiangong',
  issLabel: 'ISS · {v} km/h',
  waiting: 'Warte auf Position …',
  stand: 'Stand: {ago}',
  justNow: 'gerade eben',
  minAgo: 'vor {n} min',
  hAgo: 'vor {n} h',
  dAgo: 'vor {n} Tagen',
  stale: 'veraltet',
  offline: 'offline',
  retry: 'Erneut versuchen',
  loading: 'Lade …',
  source: 'Daten: {src}',
  more: 'Mehr',
  less: 'Weniger',
  'geo.unsupported': 'Dein Browser unterstützt keine Standortabfrage.',
  'geo.denied': 'Standort nicht freigegeben – kein Problem, die ISS fliegt trotzdem.',
  'geo.unavailable': 'Standort gerade nicht bestimmbar.',
  'geo.timeout': 'Standortabfrage hat zu lange gedauert.',
  'geo.locating': 'Suche Standort …',
  'geo.result': 'Die ISS ist gerade <b>{deg}°</b> {rel} deinem Horizont · <b>{dist} km</b> entfernt',
  'geo.above': 'über',
  'geo.below': 'unter',
  'geo.visible': 'Sichtbar, wenn sie in der Sonne steht und bei dir Nacht ist.',
  you: 'Du',
  'iss.sub': 'Internationale Raumstation',
  'iss.since': 'Im Orbit seit',
  'iss.period': 'Umlaufzeit',
  'iss.mass': 'Masse',
  'iss.size': 'Spannweite',
  'iss.crew': 'Besatzung',
  'iss.visibility': 'Sichtbarkeit',
  'iss.blurb': 'Das grösste je gebaute Raumfahrzeug: 109 m breit, 420 Tonnen, seit November 2000 ununterbrochen bewohnt. Sie umrundet die Erde alle 93 Minuten – 16 Sonnenaufgänge pro Tag.',
  'iss.hidden': 'hinter der Erde',
  tapCoords: '{lat} · {lon}',
  north: 'N', south: 'S', east: 'O', west: 'W',

  'crew.title': 'Menschen im All',
  'crew.source': 'The Space Devs – Launch Library 2',
  'crew.now': 'gerade im All',
  'crew.iss': 'ISS',
  'crew.tiangong': 'Tiangong',
  'crew.heuristic': 'Zuordnung nach Agentur: CNSA → Tiangong, alle anderen → ISS (Heuristik).',
  'crew.flights': 'Flüge',
  'crew.evas': 'Aussenbordeinsätze',
  'crew.firstFlight': 'Erster Flug',
  'crew.station': 'Station',
  'crew.wiki': 'Wikipedia',
  'crew.none': 'Im Moment ist niemand im All.',

  'launches.title': 'Nächste Starts',
  'launches.source': 'The Space Devs – Launch Library 2',
  'launches.next': 'Nächster Start',
  'launches.launched': 'gestartet',
  'launches.webcast': 'Webcast',
  'launches.mission': 'Mission',
  'launches.none': 'Keine Starts angekündigt.',
  'launches.status.go': 'Go',
  'launches.status.tbc': 'Unbestätigt',
  'launches.status.tbd': 'Datum offen',
  'launches.status.hold': 'Hold',
  'launches.status.success': 'Erfolg',
  'launches.status.failure': 'Fehlschlag',
  'launches.status.inflight': 'Im Flug',

  'weather.title': 'Weltraumwetter',
  'weather.source': 'NOAA Space Weather Prediction Center',
  'weather.kp': 'Kp-Index',
  'weather.kpExplain': 'Kp misst, wie stark der Sonnenwind das Erdmagnetfeld stört: 0 ruhig, 9 extremer Sturm. Ab Kp 5 sind Polarlichter bis in die Alpen möglich.',
  'weather.wind': 'Sonnenwind',
  'weather.density': 'Dichte',
  'weather.bz': 'Bz (IMF)',
  'weather.bzNote': 'negativ = Polarlicht-günstig',
  'weather.bt': 'Bt',
  'weather.f107': 'F10.7',
  'weather.f107Note': 'Radiofluss (sfu)',
  'weather.last24': 'Kp – letzte 24 Stunden',
  'weather.storm': 'Sturm',
  'weather.quiet': 'ruhig',
  'weather.na': '–',

  'sun.title': 'Die Sonne jetzt',
  'sun.source': 'NASA Solar Dynamics Observatory',
  'sun.aia171': '<b>AIA 171 Å</b> · Korona, 600’000 °C – Magnetfeldbögen über aktiven Regionen.',
  'sun.aia304': '<b>AIA 304 Å</b> · Chromosphäre, 50’000 °C – Protuberanzen am Sonnenrand.',
  'sun.aia193': '<b>AIA 193 Å</b> · Heisse Korona, 1 Mio. °C – dunkle koronale Löcher.',
  'sun.hmi': '<b>HMI</b> · Sichtbares Licht – Sonnenflecken, kühler und dunkler als ihre Umgebung.',
  'sun.refresh': 'Bild alle 15 Minuten neu',
  'sun.noimg': 'Bild nicht verfügbar',

  'neo.title': 'Asteroiden diese Woche',
  'neo.source': 'NASA NeoWs · JPL',
  'neo.name': 'Objekt',
  'neo.when': 'Annäherung',
  'neo.size': 'Grösse',
  'neo.miss': 'Abstand',
  'neo.speed': 'Tempo',
  'neo.hazard': 'potenziell gefährlich',
  'neo.closest': 'am nächsten',
  'neo.ld': 'LD',
  'neo.ldNote': 'LD = Mondentfernung (384’400 km)',
  'neo.demo': 'DEMO_KEY: max. 30 Abfragen pro Stunde – eigener Schlüssel unter Einstellungen.',
  'neo.jpl': 'JPL-Datenbank',
  'neo.count': '{n} Annäherungen in den nächsten 7 Tagen',
  'neo.absMag': 'Absolute Helligkeit',
  'neo.none': 'Keine Annäherungen gemeldet.',
  'neo.diameter': 'Durchmesser',
  'neo.missAu': 'Abstand (AE)',

  'apod.title': 'Bild des Tages',
  'apod.source': 'NASA Astronomy Picture of the Day',
  'apod.credit': 'Bild: {c}',
  'apod.enNote': 'Erklärung im englischen Original',
  'apod.openHd': 'Volle Auflösung',
  'apod.video': 'Heute ist das Bild ein Video – auf apod.nasa.gov ansehen.',

  'video.title': 'Live-Video der Erde',
  'video.source': 'Sen (YouTube)',
  'video.play': 'Live-Video laden',
  'video.note': 'Lädt einen YouTube-Stream von Sen: 4K-Kameras aussen an der ISS.',
  'video.credit': 'Video: Sen',
  'video.open': 'sen.com/live',

  'moon.title': 'Mond heute',
  'moon.source': 'Berechnet (Schlyter), Textur NASA',
  'moon.illum': 'Beleuchtet',
  'moon.age': 'Alter',
  'moon.days': '{n} Tage',
  'moon.dist': 'Entfernung',
  'moon.nextFull': 'Nächster Vollmond',
  'moon.nextNew': 'Nächster Neumond',
  'moon.view': 'Ansicht von der Nordhalbkugel',
  'moon.phase.new': 'Neumond',
  'moon.phase.waxCrescent': 'Zunehmende Sichel',
  'moon.phase.firstQ': 'Erstes Viertel',
  'moon.phase.waxGibbous': 'Zunehmender Mond',
  'moon.phase.full': 'Vollmond',
  'moon.phase.wanGibbous': 'Abnehmender Mond',
  'moon.phase.lastQ': 'Letztes Viertel',
  'moon.phase.wanCrescent': 'Abnehmende Sichel',

  'deep.title': 'Tiefer Raum jetzt',
  'deep.source': 'JPL-Bahnelemente, im Browser berechnet',
  'deep.fromEarth': 'von der Erde',
  'deep.fromSun': 'von der Sonne',
  'deep.light': 'Funksignal',
  'deep.launched': 'Start',
  'deep.daysSince': 'Tage seit',
  'deep.jwst': 'JWST-Start',
  'deep.apollo': 'Apollo 11',
  'deep.sputnik': 'Sputnik 1',
  'deep.lightTitle': 'Licht, das jetzt ankommt',
  'deep.lightSun': 'Das Sonnenlicht, das jetzt die Erde erreicht, startete vor <b>{t}</b>.',
  'deep.lightMoon': 'Das Mondlicht ist <b>{t}</b> alt.',
  'deep.lightProxima': 'Das Licht von Proxima Centauri, unserem nächsten Stern, startete vor <b>{t}</b>.',
  'deep.lightAndromeda': 'Das Licht der Andromeda-Galaxie startete vor <b>{t}</b> – bevor es Menschen gab.',
  'deep.years': '{y} Jahre',

  'settings.title': 'Einstellungen',
  'settings.source': 'Lokal gespeichert (localStorage)',
  'settings.key': 'NASA API-Schlüssel',
  'settings.keyNote': 'Ohne eigenen Schlüssel laufen Asteroiden und Bild des Tages über DEMO_KEY: 30 Abfragen pro Stunde, 50 pro Tag – geteilt mit allen hinter derselben IP. Ein kostenloser Schlüssel gilt ab der nächsten Abfrage.',
  'settings.getKey': 'Schlüssel holen: api.nasa.gov',
  'settings.save': 'Speichern',
  'settings.saved': 'Schlüssel gespeichert',
  'settings.removed': 'Schlüssel entfernt – zurück zu DEMO_KEY',
  'settings.refreshAll': 'Alle Daten aktualisieren',
  'settings.autoRotate': 'Auto-Rotation',
  'settings.pollNote': 'Abfragen pausieren, solange der Tab im Hintergrund ist. ISS alle 5 s, Wetter alle 10 min, Starts alle 30 min.',
}, {
  kicker: 'Chapter 8 · KOSMOS',
  hint: 'Drag to rotate · Scroll for more · Tap for details',
  live: 'Live',
  heroSub: 'The International Space Station, right now: 400 km up, 28,000 km/h. Below: who is in space, what launches next, how hard the Sun is blowing.',
  whereAmI: 'Where am I?',
  centerIss: 'Centre ISS',
  followIss: 'Follow ISS',
  scrollDown: 'More live data',
  'stat.alt': 'Altitude · km',
  'stat.speed': 'Speed · km/h',
  'stat.pos': 'Position',
  'stat.daynight': 'Day / night',
  'stat.orbits': 'Orbits since 1998',
  'stat.people': 'People in space',
  day: 'Day',
  night: 'Night',
  sunlit: 'in sunlight',
  eclipsed: 'in Earth’s shadow',
  approx: 'approx. · 15.5 per day',
  aboard: 'aboard ISS & Tiangong',
  issLabel: 'ISS · {v} km/h',
  waiting: 'Waiting for position …',
  stand: 'As of: {ago}',
  justNow: 'just now',
  minAgo: '{n} min ago',
  hAgo: '{n} h ago',
  dAgo: '{n} days ago',
  stale: 'stale',
  offline: 'offline',
  retry: 'Retry',
  loading: 'Loading …',
  source: 'Data: {src}',
  more: 'More',
  less: 'Less',
  'geo.unsupported': 'Your browser does not support geolocation.',
  'geo.denied': 'Location not shared – no problem, the ISS keeps flying.',
  'geo.unavailable': 'Location unavailable right now.',
  'geo.timeout': 'Location request timed out.',
  'geo.locating': 'Locating …',
  'geo.result': 'The ISS is <b>{deg}°</b> {rel} your horizon right now · <b>{dist} km</b> away',
  'geo.above': 'above',
  'geo.below': 'below',
  'geo.visible': 'Visible when it is in sunlight and it is night where you are.',
  you: 'You',
  'iss.sub': 'International Space Station',
  'iss.since': 'In orbit since',
  'iss.period': 'Orbital period',
  'iss.mass': 'Mass',
  'iss.size': 'Span',
  'iss.crew': 'Crew',
  'iss.visibility': 'Visibility',
  'iss.blurb': 'The largest spacecraft ever built: 109 m wide, 420 tonnes, continuously inhabited since November 2000. It circles Earth every 93 minutes – 16 sunrises a day.',
  'iss.hidden': 'behind Earth',
  tapCoords: '{lat} · {lon}',
  north: 'N', south: 'S', east: 'E', west: 'W',

  'crew.title': 'People in space',
  'crew.source': 'The Space Devs – Launch Library 2',
  'crew.now': 'in space right now',
  'crew.iss': 'ISS',
  'crew.tiangong': 'Tiangong',
  'crew.heuristic': 'Assigned by agency: CNSA → Tiangong, everyone else → ISS (a heuristic).',
  'crew.flights': 'Flights',
  'crew.evas': 'Spacewalks',
  'crew.firstFlight': 'First flight',
  'crew.station': 'Station',
  'crew.wiki': 'Wikipedia',
  'crew.none': 'Nobody is in space at the moment.',

  'launches.title': 'Next launches',
  'launches.source': 'The Space Devs – Launch Library 2',
  'launches.next': 'Next launch',
  'launches.launched': 'launched',
  'launches.webcast': 'Webcast',
  'launches.mission': 'Mission',
  'launches.none': 'No launches announced.',
  'launches.status.go': 'Go',
  'launches.status.tbc': 'To be confirmed',
  'launches.status.tbd': 'Date TBD',
  'launches.status.hold': 'Hold',
  'launches.status.success': 'Success',
  'launches.status.failure': 'Failure',
  'launches.status.inflight': 'In flight',

  'weather.title': 'Space weather',
  'weather.source': 'NOAA Space Weather Prediction Center',
  'weather.kp': 'Kp index',
  'weather.kpExplain': 'Kp measures how much the solar wind disturbs Earth’s magnetic field: 0 quiet, 9 extreme storm. From Kp 5, aurorae reach the Alps.',
  'weather.wind': 'Solar wind',
  'weather.density': 'Density',
  'weather.bz': 'Bz (IMF)',
  'weather.bzNote': 'negative = aurora-friendly',
  'weather.bt': 'Bt',
  'weather.f107': 'F10.7',
  'weather.f107Note': 'radio flux (sfu)',
  'weather.last24': 'Kp – last 24 hours',
  'weather.storm': 'storm',
  'weather.quiet': 'quiet',
  'weather.na': '–',

  'sun.title': 'The Sun right now',
  'sun.source': 'NASA Solar Dynamics Observatory',
  'sun.aia171': '<b>AIA 171 Å</b> · Corona, 600,000 °C – magnetic loops above active regions.',
  'sun.aia304': '<b>AIA 304 Å</b> · Chromosphere, 50,000 °C – prominences on the limb.',
  'sun.aia193': '<b>AIA 193 Å</b> · Hot corona, 1 million °C – dark coronal holes.',
  'sun.hmi': '<b>HMI</b> · Visible light – sunspots, cooler and darker than their surroundings.',
  'sun.refresh': 'New image every 15 minutes',
  'sun.noimg': 'Image unavailable',

  'neo.title': 'Asteroids this week',
  'neo.source': 'NASA NeoWs · JPL',
  'neo.name': 'Object',
  'neo.when': 'Approach',
  'neo.size': 'Size',
  'neo.miss': 'Miss distance',
  'neo.speed': 'Speed',
  'neo.hazard': 'potentially hazardous',
  'neo.closest': 'closest',
  'neo.ld': 'LD',
  'neo.ldNote': 'LD = lunar distance (384,400 km)',
  'neo.demo': 'DEMO_KEY: max. 30 requests per hour – add your own key under Settings.',
  'neo.jpl': 'JPL database',
  'neo.count': '{n} close approaches in the next 7 days',
  'neo.absMag': 'Absolute magnitude',
  'neo.none': 'No close approaches reported.',
  'neo.diameter': 'Diameter',
  'neo.missAu': 'Miss distance (AU)',

  'apod.title': 'Picture of the day',
  'apod.source': 'NASA Astronomy Picture of the Day',
  'apod.credit': 'Image: {c}',
  'apod.enNote': 'Explanation in the original English',
  'apod.openHd': 'Full resolution',
  'apod.video': 'Today’s picture is a video – watch it on apod.nasa.gov.',

  'video.title': 'Live video of Earth',
  'video.source': 'Sen (YouTube)',
  'video.play': 'Load live video',
  'video.note': 'Loads a YouTube stream by Sen: 4K cameras mounted outside the ISS.',
  'video.credit': 'Video: Sen',
  'video.open': 'sen.com/live',

  'moon.title': 'The Moon today',
  'moon.source': 'Computed (Schlyter), texture NASA',
  'moon.illum': 'Illuminated',
  'moon.age': 'Age',
  'moon.days': '{n} days',
  'moon.dist': 'Distance',
  'moon.nextFull': 'Next full moon',
  'moon.nextNew': 'Next new moon',
  'moon.view': 'As seen from the northern hemisphere',
  'moon.phase.new': 'New moon',
  'moon.phase.waxCrescent': 'Waxing crescent',
  'moon.phase.firstQ': 'First quarter',
  'moon.phase.waxGibbous': 'Waxing gibbous',
  'moon.phase.full': 'Full moon',
  'moon.phase.wanGibbous': 'Waning gibbous',
  'moon.phase.lastQ': 'Last quarter',
  'moon.phase.wanCrescent': 'Waning crescent',

  'deep.title': 'Deep space right now',
  'deep.source': 'JPL orbital elements, computed in the browser',
  'deep.fromEarth': 'from Earth',
  'deep.fromSun': 'from the Sun',
  'deep.light': 'Radio signal',
  'deep.launched': 'Launched',
  'deep.daysSince': 'Days since',
  'deep.jwst': 'JWST launch',
  'deep.apollo': 'Apollo 11',
  'deep.sputnik': 'Sputnik 1',
  'deep.lightTitle': 'Light arriving right now',
  'deep.lightSun': 'The sunlight reaching Earth right now left the Sun <b>{t}</b> ago.',
  'deep.lightMoon': 'Moonlight is <b>{t}</b> old.',
  'deep.lightProxima': 'The light from Proxima Centauri, our nearest star, set out <b>{t}</b> ago.',
  'deep.lightAndromeda': 'The light of the Andromeda Galaxy set out <b>{t}</b> ago – before there were humans.',
  'deep.years': '{y} years',

  'settings.title': 'Settings',
  'settings.source': 'Stored locally (localStorage)',
  'settings.key': 'NASA API key',
  'settings.keyNote': 'Without your own key, asteroids and the picture of the day use DEMO_KEY: 30 requests per hour, 50 per day – shared with everyone behind the same IP. A free key applies from the next request.',
  'settings.getKey': 'Get a key: api.nasa.gov',
  'settings.save': 'Save',
  'settings.saved': 'Key saved',
  'settings.removed': 'Key removed – back to DEMO_KEY',
  'settings.refreshAll': 'Refresh all data',
  'settings.autoRotate': 'Auto-rotate',
  'settings.pollNote': 'Polling pauses while the tab is in the background. ISS every 5 s, weather every 10 min, launches every 30 min.',
});
