import { registerStrings } from '../../core/i18n';

/**
 * Strings of the galaxies chapter (namespace `galaxies`). German first (de-CH: «ss», ’ as thousands separator),
 * then English. Tone: sober, precise, enthusiastic – short sentences, real numbers.
 */
registerStrings('galaxies', {
  kicker: 'Kapitel 4 · KOSMOS',
  introHint: 'Ziehen zum Drehen · Scrollen zum Zoomen · Galaxie antippen für Details',

  // stats
  statGalaxies: 'Galaxien',
  statGalaxiesSub: '2MASS Redshift Survey, der ganze Himmel',
  statReach: 'Reichweite der Karte',
  statReachSub: '3 % des Radius des beobachtbaren Universums',
  statMw: '1 von ~2 Billionen',
  statMwL: 'Milchstrasse',
  statMwSub: 'Galaxien im beobachtbaren Universum',
  src: 'Daten: 2MASS Redshift Survey (Huchra et al. 2012), H₀ = 70',

  // controls
  ctlTitle: 'Karte',
  limit: 'Reichweite',
  chipCz: 'Farbe = Fluchtgeschwindigkeit',
  chipPlane: 'Galaktische Ebene',
  chipMarks: 'Landmarken',
  chipFly: 'Freiflug',
  legendType: '<i class="sw e"></i> elliptisch / linsenförmig <i class="sw s"></i> Spirale <i class="sw i"></i> irregulär <i class="sw u"></i> unbekannt',
  legendCz: '<i class="sw b"></i> nah, nähert sich <i class="sw w"></i> Hubble-Fluss <i class="sw r"></i> fern, 50’000 km/s',
  czNote: 'Hubbles Gesetz: Je weiter eine Galaxie entfernt ist, desto schneller entfernt sie sich – v = H₀ · d. Die Farbe zeigt die Fluchtgeschwindigkeit cz: blau nah, rot fern.',
  planeNote: '<b>Zone der Vermeidung.</b> Entlang der Milchstrassenebene verdecken Staub und Sterne unserer eigenen Galaxie den Blick nach draussen. Der leere Streifen ist kein Loch im Universum – er ist unser blinder Fleck.',
  flyNote: '<kbd>W</kbd><kbd>A</kbd><kbd>S</kbd><kbd>D</kbd> fliegen · Ziehen zum Umsehen · Scrollen für Tempo · <kbd>Shift</kbd> Turbo',
  flyForward: 'Vorwärts',

  // HUD
  hudDist: 'Abstand zur Milchstrasse',
  hudVisible: 'Galaxien im Umkreis',
  hudSpeed: 'Tempo',
  hudPerSec: '/s',
  hudHint: 'Ziehen · Scrollen · Antippen',

  // tour
  tourTitle: 'Reise durch das kosmische <em>Netz</em>',
  tourSub: 'Neun Stationen: von der Milchstrasse bis zum Rand der Karte.',
  tourStart: 'Reise starten',
  tourStation: 'Station',
  tourNext: 'Weiter',
  tourPrev: 'Zurück',
  tourPause: 'Pause',
  tourPlay: 'Weiter abspielen',
  tourEnd: 'Reise beenden',
  tourFlying: 'Flug nach {name} …',
  tourDone: 'Ende der Reise. Die Karte gehört dir.',
  lightStart: 'Dieses Licht startete, als {event}.',
  lightNow: 'Das Licht aus dem Zentrum der Milchstrasse ist 26’000 Jahre unterwegs – es startete, als {event}.',

  // epochs (fill the sentence «Dieses Licht startete, als …»)
  'epoch.1000': 'es auf der Erde nur einzellige Lebewesen gab',
  'epoch.540': 'die kambrische Explosion noch bevorstand – Tiere gab es noch keine',
  'epoch.300': 'im Karbon Steinkohlewälder wuchsen und Rieseninsekten flogen',
  'epoch.200': 'in der Trias die ersten Dinosaurier auftauchten',
  'epoch.66': 'in der Kreidezeit Dinosaurier die Erde beherrschten',
  'epoch.34': 'im Eozän die ersten Wale ins Meer zurückkehrten',
  'epoch.5': 'im Miozän die ersten Menschenaffen lebten',
  'epoch.2': 'die ersten Werkzeuge der Gattung Homo entstanden',
  'epoch.0.2': 'Homo erectus durch Afrika und Asien zog',
  'epoch.0.1': 'der moderne Mensch gerade erst entstanden war',
  'epoch.0.02': 'die letzte Eiszeit ihren Höhepunkt erreichte',
  'epoch.0': 'Menschen die ersten Städte bauten',

  // tour stops
  'stop.milkyway.title': 'Milch<em>strasse</em>',
  'stop.milkyway.text': 'Du bist hier: 26’000 Lichtjahre vom Zentrum, in einem Seitenarm. Die Scheibe misst 100’000 Lichtjahre – auf dieser Karte ein winziger Fleck. Zoome hinaus, und sie verschwindet zwischen 43’000 anderen.',
  'stop.m31.title': 'Andromeda',
  'stop.localgroup.title': 'Lokale <em>Gruppe</em>',
  'stop.virgo.title': 'Virgo-<em>Haufen</em>',
  'stop.virgo.text': 'Der nächste grosse Galaxienhaufen: 1’300 Galaxien, in der Mitte die Riesengalaxie M87 mit einem Schwarzen Loch von 6,5 Milliarden Sonnenmassen – dem ersten, das je fotografiert wurde.',
  'stop.norma.title': 'Laniakea · Grosser <em>Attraktor</em>',
  'stop.norma.text': 'Unser Superhaufen: 100’000 Galaxien, deren Bewegung auf einen Punkt zeigt – den Grossen Attraktor beim Norma-Haufen, versteckt hinter der Milchstrassenebene. Auch wir fallen mit 600 km/s dorthin.',
  'stop.coma.title': 'Coma-<em>Haufen</em>',
  'stop.coma.text': 'Tausend Galaxien, 320 Millionen Lichtjahre entfernt. Hier bemerkte Fritz Zwicky 1933, dass die Galaxien viel zu schnell sind für die sichtbare Masse – die erste Spur der Dunklen Materie.',
  'stop.perseuspisces.title': 'Perseus–<em>Pisces</em>',
  'stop.perseuspisces.text': 'Ein Faden des kosmischen Netzes, 250 Millionen Lichtjahre lang. Galaxien reihen sich entlang unsichtbarer Dunkle-Materie-Strukturen wie Tautropfen auf einem Spinnennetz.',
  'stop.shapley.title': 'Shapley-<em>Superhaufen</em>',
  'stop.shapley.text': 'Die massereichste Struktur im nahen Universum: 25 Galaxienhaufen, 10’000 Billiarden Sonnenmassen. Seine Schwerkraft zieht selbst an Laniakea.',
  'stop.edge.title': 'Rand der <em>Karte</em>',
  'stop.edge.text': 'Hier endet der 2MRS-Katalog: 1,4 Milliarden Lichtjahre. Das beobachtbare Universum reicht 30-mal weiter. Auf dieser Skala ist die Milchstrasse kleiner als ein Pixel – und jede Galaxie hier ist eine Welt aus hundert Milliarden Sonnen.',
  'edge.n1': 'Galaxien im Katalog',
  'edge.n2': 'Reichweite',
  'edge.n3': 'Radius des beobachtbaren Universums',

  // galaxy info card
  'type.0': 'Typ unbekannt',
  'type.1': 'Elliptische Galaxie',
  'type.2': 'Linsenförmige Galaxie',
  'type.3': 'Spiralgalaxie',
  'type.4': 'Irreguläre Galaxie',
  generic: '2MASS-Galaxie',
  rowDist: 'Entfernung',
  rowCz: 'Fluchtgeschwindigkeit',
  rowLight: 'Lichtlaufzeit',
  rowK: 'Helligkeit (K-Band)',
  rowType: 'Typ',
  approaching: 'nähert sich',
  hubbleNote: 'Hubble-Fluss: v ≈ H₀ · d, Entfernung aus der Rotverschiebung.',
  directNote: 'Entfernung direkt gemessen (Cepheiden / TRGB / SBF) – so nah dominiert die Eigenbewegung.',
  flyThere: 'Dorthin fliegen',
  cardSrc: '2MRS · Huchra et al. 2012',
  'kind.cluster': 'Galaxienhaufen',
  'kind.supercluster': 'Superhaufen',
  'kind.galaxy': 'Galaxie',
  'kind.void': 'Leerraum (Void)',
  'kind.wall': 'Grosse Mauer',
  mwLabel: 'Milchstrasse (du bist hier)',
  sun: 'Sonne',
  notFound: 'Nicht gefunden: {q}',
}, {
  kicker: 'Chapter 4 · KOSMOS',
  introHint: 'Drag to rotate · Scroll to zoom · Tap a galaxy for details',

  statGalaxies: 'galaxies',
  statGalaxiesSub: '2MASS Redshift Survey, the whole sky',
  statReach: 'Reach of the map',
  statReachSub: '3 % of the radius of the observable universe',
  statMw: '1 of ~2 trillion',
  statMwL: 'Milky Way',
  statMwSub: 'galaxies in the observable universe',
  src: 'Data: 2MASS Redshift Survey (Huchra et al. 2012), H₀ = 70',

  ctlTitle: 'Map',
  limit: 'Reach',
  chipCz: 'Colour = recession velocity',
  chipPlane: 'Galactic plane',
  chipMarks: 'Landmarks',
  chipFly: 'Free flight',
  legendType: '<i class="sw e"></i> elliptical / lenticular <i class="sw s"></i> spiral <i class="sw i"></i> irregular <i class="sw u"></i> unknown',
  legendCz: '<i class="sw b"></i> near, approaching <i class="sw w"></i> Hubble flow <i class="sw r"></i> far, 50,000 km/s',
  czNote: 'Hubble’s law: the farther away a galaxy is, the faster it recedes – v = H₀ · d. Colour shows the recession velocity cz: blue near, red far.',
  planeNote: '<b>Zone of avoidance.</b> Along the plane of the Milky Way, the dust and stars of our own galaxy block the view outwards. The empty strip is not a hole in the universe – it is our blind spot.',
  flyNote: '<kbd>W</kbd><kbd>A</kbd><kbd>S</kbd><kbd>D</kbd> fly · Drag to look · Scroll for speed · <kbd>Shift</kbd> boost',
  flyForward: 'Forward',

  hudDist: 'Distance from the Milky Way',
  hudVisible: 'galaxies within reach',
  hudSpeed: 'Speed',
  hudPerSec: '/s',
  hudHint: 'Drag · Scroll · Tap',

  tourTitle: 'Journey through the cosmic <em>web</em>',
  tourSub: 'Nine stops: from the Milky Way to the edge of the map.',
  tourStart: 'Start the journey',
  tourStation: 'Stop',
  tourNext: 'Next',
  tourPrev: 'Back',
  tourPause: 'Pause',
  tourPlay: 'Resume',
  tourEnd: 'End journey',
  tourFlying: 'Flying to {name} …',
  tourDone: 'End of the journey. The map is yours.',
  lightStart: 'This light set out when {event}.',
  lightNow: 'Light from the centre of the Milky Way travels 26,000 years – it set out when {event}.',

  'epoch.1000': 'Earth had only single-celled life',
  'epoch.540': 'the Cambrian explosion was still to come – there were no animals yet',
  'epoch.300': 'coal forests grew and giant insects flew in the Carboniferous',
  'epoch.200': 'the first dinosaurs appeared in the Triassic',
  'epoch.66': 'dinosaurs ruled the Cretaceous Earth',
  'epoch.34': 'the first whales returned to the sea in the Eocene',
  'epoch.5': 'the first great apes lived in the Miocene',
  'epoch.2': 'the first tools of the genus Homo were made',
  'epoch.0.2': 'Homo erectus roamed Africa and Asia',
  'epoch.0.1': 'modern humans had only just emerged',
  'epoch.0.02': 'the last ice age reached its peak',
  'epoch.0': 'people were building the first cities',

  'stop.milkyway.title': 'Milky <em>Way</em>',
  'stop.milkyway.text': 'You are here: 26,000 light-years from the centre, in a minor arm. The disc spans 100,000 light-years – on this map, a tiny speck. Zoom out and it vanishes among 43,000 others.',
  'stop.m31.title': 'Andromeda',
  'stop.localgroup.title': 'Local <em>Group</em>',
  'stop.virgo.title': 'Virgo <em>Cluster</em>',
  'stop.virgo.text': 'The nearest large cluster of galaxies: 1,300 members, at its heart the giant M87 with a black hole of 6.5 billion solar masses – the first ever photographed.',
  'stop.norma.title': 'Laniakea · Great <em>Attractor</em>',
  'stop.norma.text': 'Our supercluster: 100,000 galaxies whose motions point at one spot – the Great Attractor near the Norma Cluster, hidden behind the plane of the Milky Way. We too fall towards it at 600 km/s.',
  'stop.coma.title': 'Coma <em>Cluster</em>',
  'stop.coma.text': 'A thousand galaxies, 320 million light-years away. Here, in 1933, Fritz Zwicky noticed that the galaxies move far too fast for the visible mass – the first trace of dark matter.',
  'stop.perseuspisces.title': 'Perseus–<em>Pisces</em>',
  'stop.perseuspisces.text': 'A filament of the cosmic web, 250 million light-years long. Galaxies line up along invisible structures of dark matter like dewdrops on a spider’s web.',
  'stop.shapley.title': 'Shapley <em>Supercluster</em>',
  'stop.shapley.text': 'The most massive structure in the nearby universe: 25 galaxy clusters, 10,000 quadrillion solar masses. Its gravity tugs even at Laniakea.',
  'stop.edge.title': 'Edge of the <em>Map</em>',
  'stop.edge.text': 'Here the 2MRS catalogue ends: 1.4 billion light-years. The observable universe reaches 30 times farther. At this scale the Milky Way is smaller than a pixel – and every galaxy here is a world of a hundred billion suns.',
  'edge.n1': 'Galaxies in the catalogue',
  'edge.n2': 'Reach',
  'edge.n3': 'Radius of the observable universe',

  'type.0': 'Type unknown',
  'type.1': 'Elliptical galaxy',
  'type.2': 'Lenticular galaxy',
  'type.3': 'Spiral galaxy',
  'type.4': 'Irregular galaxy',
  generic: '2MASS galaxy',
  rowDist: 'Distance',
  rowCz: 'Recession velocity',
  rowLight: 'Light travel time',
  rowK: 'Brightness (K band)',
  rowType: 'Type',
  approaching: 'approaching',
  hubbleNote: 'Hubble flow: v ≈ H₀ · d, distance from the redshift.',
  directNote: 'Distance measured directly (Cepheids / TRGB / SBF) – this close, peculiar motion dominates.',
  flyThere: 'Fly there',
  cardSrc: '2MRS · Huchra et al. 2012',
  'kind.cluster': 'Galaxy cluster',
  'kind.supercluster': 'Supercluster',
  'kind.galaxy': 'Galaxy',
  'kind.void': 'Void',
  'kind.wall': 'Great wall',
  mwLabel: 'Milky Way (you are here)',
  sun: 'Sun',
  notFound: 'Not found: {q}',
});
