import { registerStrings } from '../../core/i18n';

/** Chapter strings – German first, then English. Keys become `solarsystem.<key>`. */
registerStrings('solarsystem', {
  kicker: 'Kapitel 2 · KOSMOS',
  hint: 'Ziehen zum Drehen · Scrollen zum Zoomen · Körper antippen für Details · Zeit unten steuern',
  bodies: 'Körper',
  overview: 'Übersicht',
  scale: 'Massstab',
  scaleVisible: 'sichtbar',
  scaleTrue: 'echt',
  orbits: 'Bahnen',
  names: 'Namen',
  'kind.star': 'Stern',
  'kind.planet': 'Planet',
  'kind.dwarf': 'Zwergplanet',
  'kind.comet': 'Komet',
  'kind.moon': 'Mond',
  'kind.probe': 'Sonde',
  'kind.belt': 'Gürtel · schematisch',
  time: 'Zeit',
  now: 'Jetzt',
  play: 'Abspielen',
  pause: 'Pause',
  stepBack: 'Einen Schritt zurück',
  stepFwd: 'Einen Schritt vor',
  'speed.s': '1 s/s',
  'speed.min': '1 min/s',
  'speed.h': '1 h/s',
  'speed.d': '1 Tag/s',
  'speed.w': '1 Woche/s',
  'speed.mo': '1 Monat/s',
  'speed.y': '1 Jahr/s',
  realtime: 'Echtzeit',
  date: 'Datum',
  birthday: 'Mein Geburtstag',
  show: 'Zeigen',
  birthdayToast: 'So stand das Sonnensystem, als du <em>geboren</em> wurdest.',
  rangeHint: 'Die Bahnelemente der NASA gelten nur für 1800–2050 – Datum angepasst.',
  trueToast: 'Echter Massstab: Die Planeten werden zu Punkten. Das Sonnensystem ist fast nur Leere.',
  visibleToast: 'Sichtbarer Massstab: Grössen logarithmisch überhöht, Abstände echt.',
  live: 'Jetzt gerade',
  earthSun: 'Erde–Sonne',
  lightSunEarth: 'Licht Sonne → Erde',
  earthMars: 'Erde–Mars',
  earthJupiter: 'Erde–Jupiter',
  v1: 'Voyager 1',
  v1dist: 'Voyager 1 – Erde',
  v1light: 'Funksignal Voyager 1 → Erde',
  mioKm: 'Mio. km',
  au: 'AE',
  radius: 'Radius',
  mass: 'Masse',
  day: 'Tag (Rotation)',
  year: 'Jahr (Umlauf)',
  temperature: 'Temperatur',
  moons: 'Monde',
  gravity: 'Schwerkraft',
  distSun: 'Zur Sonne jetzt',
  distEarth: 'Zur Erde jetzt',
  lightEarth: 'Lichtlaufzeit zur Erde',
  speed: 'Geschwindigkeit',
  retrograde: 'rückläufig',
  xEarth: '× Erde',
  earthYears: 'Erdjahre',
  days: 'Tage',
  hours: 'h',
  source: 'Bahnelemente: NASA/JPL',
  sourceLive: 'Positionen: NASA/JPL-Keplerelemente · heliozentrisch-ekliptisch',
  sourceBelt: 'Gürtel schematisch · Grössenordnungen: NASA/JPL',
  'asteroids.name': 'Asteroidengürtel',
  'asteroids.blurb': 'Zwischen Mars und Jupiter kreisen Millionen Gesteinsbrocken – doch ihre Gesamtmasse beträgt nur 3 % der Mondmasse. Die Punkte hier sind statistisch verteilt (schematisch), nicht einzelne Objekte.',
  'asteroids.facts': 'Über 1,3 Millionen bekannte Asteroiden.|Der grösste Körper ist der Zwergplanet Ceres (940 km).|Im Mittel liegen hunderttausende Kilometer zwischen zwei Brocken – Raumsonden fliegen gefahrlos hindurch.',
  'kuiper.name': 'Kuipergürtel',
  'kuiper.blurb': 'Jenseits von Neptun, 30 bis 50 AE von der Sonne: ein Ring aus Eiskörpern, Überreste der Planetenentstehung. Pluto, Haumea und Makemake gehören dazu. Darstellung schematisch.',
  'kuiper.facts': 'Vermutlich über 100’000 Objekte grösser als 100 km.|Kurzperiodische Kometen stammen von hier.|New Horizons besuchte 2019 das Kuipergürtel-Objekt Arrokoth.',
  schematic: 'schematisch',
  probeLine: 'Flugrichtung von der Sonne (gerade Bahn, Näherung)',
  'unit.s': 'Sekunde',
  'unit.min': 'Minute',
  'unit.h': 'Stunde',
  'unit.d': 'Tag',
  'unit.w': 'Woche',
  'unit.mo': 'Monat',
  'unit.y': 'Jahr',
  'grp.planets': 'Planeten',
  'grp.dwarfs': 'Zwergplaneten',
  'grp.small': 'Komet & Sonden',
  'grp.belts': 'Gürtel · schematisch',
  kmS: 'km/s',
  toEarth: 'Zur Erde',
  light: 'Licht',
  birthdayFuture: 'Dieses Datum liegt in der Zukunft – zeige heute.',
  keys: '<kbd>Leertaste</kbd> Play/Pause · <kbd>←</kbd><kbd>→</kbd> Schritt · <kbd>Esc</kbd> Übersicht',
  moonNote: 'Mond im sichtbaren Massstab auf 3 Erdradien gerückt',
}, {
  kicker: 'Chapter 2 · KOSMOS',
  hint: 'Drag to rotate · Scroll to zoom · Tap a body for details · Control time below',
  bodies: 'Bodies',
  overview: 'Overview',
  scale: 'Scale',
  scaleVisible: 'visible',
  scaleTrue: 'true',
  orbits: 'Orbits',
  names: 'Names',
  'kind.star': 'Star',
  'kind.planet': 'Planet',
  'kind.dwarf': 'Dwarf planet',
  'kind.comet': 'Comet',
  'kind.moon': 'Moon',
  'kind.probe': 'Probe',
  'kind.belt': 'Belt · schematic',
  time: 'Time',
  now: 'Now',
  play: 'Play',
  pause: 'Pause',
  stepBack: 'One step back',
  stepFwd: 'One step forward',
  'speed.s': '1 s/s',
  'speed.min': '1 min/s',
  'speed.h': '1 h/s',
  'speed.d': '1 day/s',
  'speed.w': '1 week/s',
  'speed.mo': '1 month/s',
  'speed.y': '1 year/s',
  realtime: 'Real time',
  date: 'Date',
  birthday: 'My birthday',
  show: 'Show',
  birthdayToast: 'This is how the solar system looked when you were <em>born</em>.',
  rangeHint: 'NASA’s orbital elements are only valid for 1800–2050 – date adjusted.',
  trueToast: 'True scale: the planets become dots. The solar system is almost entirely empty space.',
  visibleToast: 'Visible scale: sizes exaggerated logarithmically, distances real.',
  live: 'Right now',
  earthSun: 'Earth–Sun',
  lightSunEarth: 'Light Sun → Earth',
  earthMars: 'Earth–Mars',
  earthJupiter: 'Earth–Jupiter',
  v1: 'Voyager 1',
  v1dist: 'Voyager 1 – Earth',
  v1light: 'Radio signal Voyager 1 → Earth',
  mioKm: 'million km',
  au: 'AU',
  radius: 'Radius',
  mass: 'Mass',
  day: 'Day (rotation)',
  year: 'Year (orbit)',
  temperature: 'Temperature',
  moons: 'Moons',
  gravity: 'Gravity',
  distSun: 'To the Sun now',
  distEarth: 'To Earth now',
  lightEarth: 'Light time to Earth',
  speed: 'Speed',
  retrograde: 'retrograde',
  xEarth: '× Earth',
  earthYears: 'Earth years',
  days: 'days',
  hours: 'h',
  source: 'Orbital elements: NASA/JPL',
  sourceLive: 'Positions: NASA/JPL Keplerian elements · heliocentric ecliptic',
  sourceBelt: 'Belts schematic · magnitudes: NASA/JPL',
  'asteroids.name': 'Asteroid belt',
  'asteroids.blurb': 'Between Mars and Jupiter millions of rocks circle the Sun – yet their total mass is only 3% of the Moon’s. The dots here are distributed statistically (schematic), not individual objects.',
  'asteroids.facts': 'More than 1.3 million known asteroids.|The largest body is the dwarf planet Ceres (940 km).|On average hundreds of thousands of kilometres separate two rocks – probes fly through unharmed.',
  'kuiper.name': 'Kuiper belt',
  'kuiper.blurb': 'Beyond Neptune, 30 to 50 AU from the Sun: a ring of icy bodies, leftovers from planet formation. Pluto, Haumea and Makemake belong to it. Rendering is schematic.',
  'kuiper.facts': 'Probably more than 100,000 objects larger than 100 km.|Short-period comets come from here.|New Horizons visited the Kuiper-belt object Arrokoth in 2019.',
  schematic: 'schematic',
  probeLine: 'Heading away from the Sun (straight-line approximation)',
  'unit.s': 'second',
  'unit.min': 'minute',
  'unit.h': 'hour',
  'unit.d': 'day',
  'unit.w': 'week',
  'unit.mo': 'month',
  'unit.y': 'year',
  'grp.planets': 'Planets',
  'grp.dwarfs': 'Dwarf planets',
  'grp.small': 'Comet & probes',
  'grp.belts': 'Belts · schematic',
  kmS: 'km/s',
  toEarth: 'To Earth',
  light: 'Light',
  birthdayFuture: 'That date is in the future – showing today.',
  keys: '<kbd>Space</kbd> play/pause · <kbd>←</kbd><kbd>→</kbd> step · <kbd>Esc</kbd> overview',
  moonNote: 'Moon moved to 3 Earth radii in visible scale',
});
