import { registerStrings } from '../../core/i18n';

registerStrings('stars', {
  kicker: 'Kapitel 1 · KOSMOS',
  introHint: '<kbd>W</kbd><kbd>A</kbd><kbd>S</kbd><kbd>D</kbd> fliegen · Ziehen zum Umsehen · Scrollen für Tempo · Stern anklicken für Details',

  // intro stats
  statStars: 'Sterne im Katalog',
  statStarsSub: 'HYG v4.1 · Hipparcos, Gliese, Yale',
  statNearest: 'Nächster Stern',
  statNearestSub: 'Proxima Centauri, ein roter Zwerg',
  statFarthest: 'Fernster Stern im Katalog',
  statFarthestSub: 'Weiter trägt die Parallaxe nicht',

  // autopilot panel
  autopilot: 'Autopilot',
  searchPlaceholder: 'Stern suchen … (Name, HIP)',
  noResults: 'Kein Stern gefunden',
  famous: 'Berühmte Sterne',
  backToSun: 'Zurück zur Sonne',
  panelSrc: 'Daten: HYG v4.1 (Hipparcos / Gliese / Yale)',
  apTo: 'Autopilot → {name}',
  apCancelled: 'Autopilot abgebrochen – du hast das Steuer',

  // toggles
  display: 'Anzeige',
  constellations: 'Sternbilder',
  names: 'Namen',
  scale: 'Massstab',
  togglesSrc: 'Linien: Stellarium · Namen: IAU',

  // HUD
  hudDistL: 'Entfernung zur Sonne',
  hudSpeedL: 'Tempo',
  lyPerSec: 'Lj/s',
  hudProxL: 'Proxima in',
  hudStarsL: 'Sterne im Katalog',
  speed: 'Tempo',
  forward: 'Vorwärts fliegen',
  backward: 'Rückwärts fliegen',
  clickHint: 'Stern anklicken für Details · <kbd>Esc</kbd> schliesst · <kbd>H</kbd> zur Sonne',
  tapHint: 'Ziehen zum Umsehen · ▲▼ fliegen · Stern antippen',

  // info card
  sun: 'Sonne',
  sunSub: 'G2V · unser Stern',
  spectral: 'Spektraltyp',
  distSun: 'Entfernung zur Sonne',
  distYou: 'Entfernung zu dir',
  appMag: 'Scheinbare Helligkeit',
  absMag: 'Absolute Helligkeit',
  suns: '× Sonne',
  lightLeft: 'Das Licht, das du siehst, verliess diesen Stern vor <b>{years}</b>.',
  lightLeftSun: 'Das Sonnenlicht, das du auf der Erde siehst, ist <b>{t}</b> alt.',
  flyThere: 'Hinfliegen',
  arrived: 'Du bist da',
  unnamed: 'Stern',
  cardSrc: 'Daten: HYG v4.1 · Farbe aus B−V',
  landmark: 'Wegmarke',
  kindNebula: 'Emissionsnebel',
  kindCluster: 'Offener Sternhaufen',
  kindGlobular: 'Kugelsternhaufen',
  kindRemnant: 'Supernova-Überrest',
  kindCore: 'Galaktisches Zentrum',
  kindSystem: 'Sternsystem',
  kindStar: 'Stern',
  position: 'Position (RA / Dek)',
  outsideCatalog: 'ausserhalb des Katalogs',
  landmarkSrc: 'Position: SIMBAD · Entfernung: Literatur',
  ringLabel: '{n} Lichtjahre',
}, {
  kicker: 'Chapter 1 · KOSMOS',
  introHint: '<kbd>W</kbd><kbd>A</kbd><kbd>S</kbd><kbd>D</kbd> fly · Drag to look · Scroll for speed · Click a star for details',

  statStars: 'Stars in the catalogue',
  statStarsSub: 'HYG v4.1 · Hipparcos, Gliese, Yale',
  statNearest: 'Nearest star',
  statNearestSub: 'Proxima Centauri, a red dwarf',
  statFarthest: 'Farthest star in the catalogue',
  statFarthestSub: 'Beyond that, parallax stops carrying',

  autopilot: 'Autopilot',
  searchPlaceholder: 'Search star … (name, HIP)',
  noResults: 'No star found',
  famous: 'Famous stars',
  backToSun: 'Back to the Sun',
  panelSrc: 'Data: HYG v4.1 (Hipparcos / Gliese / Yale)',
  apTo: 'Autopilot → {name}',
  apCancelled: 'Autopilot cancelled – you have the controls',

  display: 'Display',
  constellations: 'Constellations',
  names: 'Names',
  scale: 'Scale',
  togglesSrc: 'Lines: Stellarium · Names: IAU',

  hudDistL: 'Distance to the Sun',
  hudSpeedL: 'Speed',
  lyPerSec: 'ly/s',
  hudProxL: 'Proxima in',
  hudStarsL: 'stars in the catalogue',
  speed: 'Speed',
  forward: 'Fly forward',
  backward: 'Fly backward',
  clickHint: 'Click a star for details · <kbd>Esc</kbd> closes · <kbd>H</kbd> back to the Sun',
  tapHint: 'Drag to look · ▲▼ to fly · Tap a star',

  sun: 'Sun',
  sunSub: 'G2V · our star',
  spectral: 'Spectral type',
  distSun: 'Distance from the Sun',
  distYou: 'Distance from you',
  appMag: 'Apparent magnitude',
  absMag: 'Absolute magnitude',
  suns: '× Sun',
  lightLeft: 'The light you see left this star <b>{years}</b> ago.',
  lightLeftSun: 'The sunlight you see on Earth is <b>{t}</b> old.',
  flyThere: 'Fly there',
  arrived: 'You are here',
  unnamed: 'Star',
  cardSrc: 'Data: HYG v4.1 · colour from B−V',
  landmark: 'Landmark',
  kindNebula: 'Emission nebula',
  kindCluster: 'Open cluster',
  kindGlobular: 'Globular cluster',
  kindRemnant: 'Supernova remnant',
  kindCore: 'Galactic centre',
  kindSystem: 'Star system',
  kindStar: 'Star',
  position: 'Position (RA / Dec)',
  outsideCatalog: 'outside the catalogue',
  landmarkSrc: 'Position: SIMBAD · distance: literature',
  ringLabel: '{n} light-years',
});
