import { registerStrings } from '../../core/i18n';

/** Zoom chapter strings – German first, then English. Milestone texts: title (with <em>), number label, two sentences. */
registerStrings('zoom', {
  kicker: 'Kapitel 5 · KOSMOS',
  introCta: 'Reise starten',
  introExplore: 'Selbst erkunden',
  hint: 'Scrollen oder <kbd>↑</kbd><kbd>↓</kbd> zoomen · Ziehen dreht den Blick · Regler rechts springt zu Mond, Sonne, Proxima …',
  hintTouch: 'Vertikal wischen zoomt · horizontal wischen dreht · Regler rechts springt zu Mond, Sonne, Proxima …',
  journey: 'Reise',
  pause: 'Pause',
  resume: 'Weiter',
  speed: 'Tempo',
  toEarth: 'Zur Erde',
  end: 'Ende der Reise – der Rand des beobachtbaren Universums.',
  scale: 'Massstab',
  distance: 'Entfernung von der Erde',
  lightTime: 'Lichtlaufzeit',
  lightNeeds: 'Licht braucht hierhin {t}',
  milestone: 'Meilenstein',
  schematic: 'schematisch',
  src: 'Daten: HYG v4.1 · 2MRS · NASA/JPL · Planck',
  srcEarth: 'Daten: NASA/JPL, Blue Marble',
  srcSolar: 'Daten: NASA/JPL Bahnelemente',
  srcStars: 'Daten: HYG v4.1 / Hipparcos',
  srcMw: 'Darstellung: schematisch (Modell)',
  srcGal: 'Daten: 2MASS Redshift Survey',
  srcCmb: 'Darstellung: schematisch (nach Planck 2018)',
  flyTo: 'Hinzoomen',
  rowDist: 'Entfernung',
  rowLight: 'Lichtlaufzeit',
  rowRadius: 'Radius',
  rowDiameter: 'Durchmesser',
  rowAlt: 'Bahnhöhe',
  rowPeriod: 'Umlaufzeit',
  rowType: 'Typ',
  rowSpeed: 'Geschwindigkeit',
  rowLaunch: 'Start',
  rowRedshift: 'Rotverschiebung',
  rowAge: 'Alter des Lichts',
  now: 'jetzt',
  // tick names (vertical slider)
  'tick.earth': 'Erde', 'tick.moon': 'Mond', 'tick.sun': 'Sonne', 'tick.neptune': 'Neptun', 'tick.voyager': 'Voyager 1',
  'tick.oort': 'Oortsche Wolke', 'tick.proxima': 'Proxima', 'tick.mw': 'Milchstrasse', 'tick.andromeda': 'Andromeda',
  'tick.virgo': 'Virgo', 'tick.laniakea': 'Laniakea', 'tick.universe': 'Universum',
  // in-scene labels
  'lbl.iss': 'ISS', 'lbl.issSub': '418 km', 'lbl.gps': 'GPS', 'lbl.gpsSub': '20’200 km', 'lbl.geo': 'Geostationär', 'lbl.geoSub': '35’786 km',
  'lbl.lightHour': '1 Lichtstunde', 'lbl.lightDay': '1 Lichttag', 'lbl.kuiper': 'Kuipergürtel', 'lbl.heliopause': 'Heliopause', 'lbl.heliopauseSub': '≈ 120 AE',
  'lbl.oort': 'Oortsche Wolke', 'lbl.oortSub': '2’000 – 100’000 AE', 'lbl.radio': 'Radioblase', 'lbl.radioSub': '100 Lichtjahre',
  'lbl.orion': 'Orion-Arm', 'lbl.sun': 'Sonne', 'lbl.earth': 'Erde', 'lbl.moon': 'Mond', 'lbl.sgra': 'Sgr A*', 'lbl.sgraSub': 'Galaktisches Zentrum',
  'lbl.mw': 'Milchstrasse', 'lbl.here': 'Hier', 'lbl.cmb': 'Kosmischer Mikrowellenhintergrund', 'lbl.cmbSub': '380’000 Jahre nach dem Urknall',
  'lbl.pleiades': 'Plejaden', 'lbl.m42': 'Orionnebel', 'lbl.alphacen': 'Alpha Centauri', 'lbl.barnard': 'Barnards Stern',
  'lbl.proxima': 'Proxima Centauri', 'lbl.wolf359': 'Wolf 359', 'lbl.sirius': 'Sirius', 'lbl.procyon': 'Procyon', 'lbl.vega': 'Wega',
  'lbl.altair': 'Altair', 'lbl.arcturus': 'Arktur', 'lbl.aldebaran': 'Aldebaran', 'lbl.betelgeuse': 'Beteigeuze', 'lbl.rigel': 'Rigel',
  'lbl.polaris': 'Polarstern', 'lbl.deneb': 'Deneb', 'lbl.lmc': 'Grosse Magellansche Wolke', 'lbl.smc': 'Kleine Magellansche Wolke',
  'lbl.m31': 'Andromeda (M31)', 'lbl.m33': 'Dreiecksgalaxie (M33)', 'lbl.gattr': 'Grosser Attraktor',
  // object blurbs (info cards)
  'obj.iss': 'Die Internationale Raumstation: 420 Tonnen, 7,66 km/s, alle 93 Minuten einmal um die Erde. Seit November 2000 ständig bewohnt.',
  'obj.gps': 'Rund 31 Satelliten auf sechs Bahnebenen, 20’200 km hoch. Ihre Atomuhren müssen die Relativitätstheorie berücksichtigen: 38 Mikrosekunden pro Tag.',
  'obj.geo': 'In 35’786 km Höhe dauert ein Umlauf genau einen Tag – die Satelliten scheinen am Himmel stillzustehen. Wetter- und Fernsehsatelliten kreisen hier.',
  'obj.lightHour': 'In einer Stunde legt Licht 1,08 Milliarden Kilometer zurück – etwa bis zur Saturnbahn.',
  'obj.lightDay': 'Ein Lichttag: 25,9 Milliarden Kilometer, rund 173 AE – bereits jenseits der Heliopause.',
  'obj.kuiper': 'Eisige Kleinkörper jenseits von Neptun, 30 bis 50 AE von der Sonne. Pluto ist der bekannteste – New Horizons flog 2015 vorbei.',
  'obj.heliopause': 'Hier trifft der Sonnenwind auf das interstellare Medium – die Blase der Sonne endet. Voyager 1 hat diese Grenze im August 2012 überquert.',
  'obj.oort': 'Der Rand des Sonnensystems: Billionen eisiger Brocken, Heimat der langperiodischen Kometen. Nie direkt beobachtet – hier beginnt der interstellare Raum.',
  'obj.radio': 'So weit sind die ersten Rundfunksignale seit den 1920ern gekommen. In dieser Blase liegen gut 10’000 Sterne – der Rest der Galaxis hat noch nie von uns gehört.',
  'obj.orion': 'Der Nebenarm der Milchstrasse, in dem die Sonne liegt – zwischen Sagittarius- und Perseus-Arm, rund 10’000 Lichtjahre lang.',
  'obj.proxima': 'Roter Zwerg, 4,24 Lichtjahre – der nächste Stern. Mit dem Planeten Proxima b in der habitablen Zone.',
  'obj.alphacen': 'Rigil Kentaurus und Toliman: zwei sonnenähnliche Sterne, die sich alle 80 Jahre umkreisen. Das dritthellste Objekt am Nachthimmel.',
  'obj.barnard': 'Der Stern mit der grössten Eigenbewegung: 10,3 Bogensekunden pro Jahr. Ein roter Zwerg, 6 Lichtjahre entfernt.',
  'obj.wolf359': 'Einer der schwächsten bekannten Sterne: ein roter Zwerg mit 9 % der Sonnenmasse.',
  'obj.sirius': 'Der hellste Stern am Nachthimmel: 25-mal leuchtkräftiger als die Sonne, begleitet vom Weissen Zwerg Sirius B.',
  'obj.procyon': 'Der achthellste Stern, 11 Lichtjahre entfernt – ebenfalls mit einem Weissen Zwerg als Begleiter.',
  'obj.vega': 'Der Eichstern der Astronomie (Helligkeit 0). Vor 12’000 Jahren war Wega der Polarstern.',
  'obj.altair': 'Rotiert so schnell (einmal in 9 Stunden), dass er am Äquator 20 % breiter ist als an den Polen.',
  'obj.arcturus': 'Ein Roter Riese, 25-mal grösser als die Sonne – der hellste Stern des Nordhimmels.',
  'obj.aldebaran': 'Das rote Auge des Stiers: ein Roter Riese, 44-mal so gross wie die Sonne.',
  'obj.betelgeuse': 'Ein Roter Überriese, so gross wie die Jupiterbahn. Er wird als Supernova enden – irgendwann in den nächsten 100’000 Jahren.',
  'obj.rigel': 'Ein blauer Überriese mit 120’000-facher Sonnenleuchtkraft, 860 Lichtjahre entfernt.',
  'obj.polaris': 'Der Polarstern: ein Überriese, 430 Lichtjahre entfernt, fast genau über dem Nordpol der Erde.',
  'obj.deneb': 'Einer der leuchtkräftigsten bekannten Sterne: 200’000 Sonnen, rund 2’600 Lichtjahre entfernt.',
  'obj.pleiades': 'Das Siebengestirn: rund 1’000 junge Sterne, 100 Millionen Jahre alt, 444 Lichtjahre entfernt.',
  'obj.m42': 'Die nächste grosse Sternentstehungsregion, 1’300 Lichtjahre entfernt – als Fleck im Schwert des Orion sichtbar.',
  'obj.sgra': 'Ein Schwarzes Loch mit 4 Millionen Sonnenmassen, 26’000 Lichtjahre entfernt. 2022 zum ersten Mal abgebildet.',
  'obj.sunStar': 'Von hier aus: ein gelber Zwergstern unter Milliarden. Sein Licht ist 8 Minuten alt, wenn es die Erde erreicht.',
  'obj.mwHere': 'Von hier aus ist die Milchstrasse ein einzelner Lichtpunkt – eine von rund 2 Billionen Galaxien im beobachtbaren Universum.',
  'obj.cmb': 'Das älteste Licht: 380’000 Jahre nach dem Urknall wurde das Universum durchsichtig. Die Flecken – ein Hunderttausendstel Grad Unterschied – sind die Keime aller Galaxien.',
  'obj.earthDot': 'Der blassblaue Punkt. Alles, was du kennst, auf einem Pixel.',
  // milestones
  'ms.moon.title': 'Der <em>Mond</em>', 'ms.moon.label': 'Entfernung jetzt',
  'ms.moon.txt': 'Unser einziger natürlicher Satellit, 30 Erddurchmesser entfernt. Zwölf Menschen sind hier gelandet – zuletzt 1972.',
  'ms.sun.title': 'Die <em>Sonne</em>', 'ms.sun.label': 'Eine Astronomische Einheit',
  'ms.sun.txt': 'Ihr Licht ist 8 Minuten und 20 Sekunden alt, wenn es uns erreicht. 99,86 % der Masse des Sonnensystems stecken in diesem einen Stern.',
  'ms.neptune.title': '<em>Neptun</em>', 'ms.neptune.label': 'Entfernung jetzt',
  'ms.neptune.txt': 'Der äusserste Planet, 30-mal weiter von der Sonne als die Erde. Von hier aus ist die Sonne nur noch ein sehr heller Stern.',
  'ms.heliopause.title': '<em>Heliopause</em>', 'ms.heliopause.num': '≈ 120 AE', 'ms.heliopause.label': 'Rand des Sonnenwinds',
  'ms.heliopause.txt': 'Hier trifft der Sonnenwind auf das interstellare Medium – die Blase der Sonne endet. Voyager 1 hat diese Grenze im August 2012 überquert.',
  'ms.voyager1.title': '<em>Voyager 1</em>', 'ms.voyager1.label': 'Entfernung jetzt',
  'ms.voyager1.txt': 'Das fernste Menschenwerk, gestartet 1977, unterwegs mit 17 km/s. Ein Funksignal braucht heute über 23 Stunden bis zur Erde.',
  'ms.oort.title': 'Oortsche <em>Wolke</em>', 'ms.oort.num': '2’000 – 100’000 AE', 'ms.oort.label': 'Ausdehnung · schematisch',
  'ms.oort.txt': 'Der Rand des Sonnensystems: Billionen eisiger Brocken, Heimat der langperiodischen Kometen. Nie direkt beobachtet – hier beginnt der interstellare Raum.',
  'ms.proxima.title': 'Proxima <em>Centauri</em>', 'ms.proxima.num': '4,24 Lichtjahre', 'ms.proxima.label': 'Der nächste Stern',
  'ms.proxima.txt': 'Ein roter Zwerg, zu schwach fürs blosse Auge, mit mindestens einem Planeten. Mit dem Tempo von Voyager dauerte die Reise 75’000 Jahre.',
  'ms.radio.title': '<em>Radioblase</em>', 'ms.radio.num': '100 Lichtjahre', 'ms.radio.label': 'Reichweite unserer Signale',
  'ms.radio.txt': 'So weit sind die ersten Rundfunksignale seit den 1920ern gekommen. In dieser Blase liegen gut 10’000 Sterne – der Rest der Galaxis hat noch nie von uns gehört.',
  'ms.orion.title': 'Orion-<em>Arm</em>', 'ms.orion.num': '10’000 Lichtjahre', 'ms.orion.label': 'Länge unseres Spiralarms',
  'ms.orion.txt': 'Der Nebenarm, in dem die Sonne liegt – zwischen Sagittarius- und Perseus-Arm. Fast jeder Stern, den du mit blossem Auge siehst, gehört dazu.',
  'ms.milkyway.title': '<em>Milchstrasse</em>', 'ms.milkyway.num': '100’000 Lichtjahre', 'ms.milkyway.label': 'Durchmesser · Modell',
  'ms.milkyway.txt': 'Eine Balkenspirale mit 100 bis 400 Milliarden Sternen. Die Sonne braucht 230 Millionen Jahre für einen Umlauf um Sagittarius A*, das Schwarze Loch im Zentrum.',
  'ms.andromeda.title': '<em>Andromeda</em>', 'ms.andromeda.num': '2,5 Mio. Lichtjahre', 'ms.andromeda.label': 'Entfernung',
  'ms.andromeda.txt': 'Die nächste grosse Galaxie und das fernste Objekt fürs blosse Auge. In rund 4,5 Milliarden Jahren verschmilzt sie mit der Milchstrasse.',
  'ms.localgroup.title': 'Lokale <em>Gruppe</em>', 'ms.localgroup.num': '≈ 80 Galaxien', 'ms.localgroup.label': 'Milchstrasse, Andromeda & Co.',
  'ms.localgroup.txt': 'Zwei grosse Spiralen, die Dreiecksgalaxie und Dutzende Zwerggalaxien, durch Gravitation gebunden – rund 10 Millionen Lichtjahre gross.',
  'ms.virgo.title': 'Virgo-<em>Haufen</em>', 'ms.virgo.num': '54 Mio. Lichtjahre', 'ms.virgo.label': 'Entfernung',
  'ms.virgo.txt': 'Über 1’300 Galaxien im Herzen unseres Superhaufens. Seine Masse bremst die Flucht der Lokalen Gruppe im expandierenden Universum.',
  'ms.edge2mrs.title': 'Rand des <em>2MRS</em>', 'ms.edge2mrs.num': '43’506 Galaxien', 'ms.edge2mrs.label': 'Echte Karte bis hierhin',
  'ms.edge2mrs.txt': 'Bis hierhin reicht die Karte des 2MASS Redshift Survey: jede Galaxie an ihrem gemessenen Ort. Alles weiter draussen ist schematisch – ein Muster, kein Katalog.',
  'ms.laniakea.title': '<em>Laniakea</em>', 'ms.laniakea.num': '520 Mio. Lichtjahre', 'ms.laniakea.label': 'Durchmesser',
  'ms.laniakea.txt': 'Unser Superhaufen: 100’000 Galaxien, die alle auf den Grossen Attraktor zuströmen. Hawaiianisch für «unermesslicher Himmel».',
  'ms.universe.title': 'Beobachtbares <em>Universum</em>', 'ms.universe.num': '46,5 Mrd. Lichtjahre', 'ms.universe.label': 'Radius',
  'ms.universe.txt': 'Die Grenze: der kosmische Mikrowellenhintergrund, das Licht von 380’000 Jahren nach dem Urknall. Dahinter kann kein Teleskop sehen – rund 2 Billionen Galaxien liegen in dieser Kugel.',
}, {
  kicker: 'Chapter 5 · KOSMOS',
  introCta: 'Start the journey',
  introExplore: 'Explore on my own',
  hint: 'Scroll or <kbd>↑</kbd><kbd>↓</kbd> to zoom · drag to turn · the slider on the right jumps to the Moon, the Sun, Proxima …',
  hintTouch: 'Swipe vertically to zoom · horizontally to turn · the slider on the right jumps to the Moon, the Sun, Proxima …',
  journey: 'Journey',
  pause: 'Pause',
  resume: 'Resume',
  speed: 'Speed',
  toEarth: 'To Earth',
  end: 'End of the journey – the edge of the observable universe.',
  scale: 'Scale',
  distance: 'Distance from Earth',
  lightTime: 'Light travel time',
  lightNeeds: 'Light takes {t} to get here',
  milestone: 'Milestone',
  schematic: 'schematic',
  src: 'Data: HYG v4.1 · 2MRS · NASA/JPL · Planck',
  srcEarth: 'Data: NASA/JPL, Blue Marble',
  srcSolar: 'Data: NASA/JPL orbital elements',
  srcStars: 'Data: HYG v4.1 / Hipparcos',
  srcMw: 'Rendering: schematic (model)',
  srcGal: 'Data: 2MASS Redshift Survey',
  srcCmb: 'Rendering: schematic (after Planck 2018)',
  flyTo: 'Zoom there',
  rowDist: 'Distance',
  rowLight: 'Light travel time',
  rowRadius: 'Radius',
  rowDiameter: 'Diameter',
  rowAlt: 'Altitude',
  rowPeriod: 'Orbital period',
  rowType: 'Type',
  rowSpeed: 'Speed',
  rowLaunch: 'Launch',
  rowRedshift: 'Redshift',
  rowAge: 'Age of the light',
  now: 'now',
  'tick.earth': 'Earth', 'tick.moon': 'Moon', 'tick.sun': 'Sun', 'tick.neptune': 'Neptune', 'tick.voyager': 'Voyager 1',
  'tick.oort': 'Oort cloud', 'tick.proxima': 'Proxima', 'tick.mw': 'Milky Way', 'tick.andromeda': 'Andromeda',
  'tick.virgo': 'Virgo', 'tick.laniakea': 'Laniakea', 'tick.universe': 'Universe',
  'lbl.iss': 'ISS', 'lbl.issSub': '418 km', 'lbl.gps': 'GPS', 'lbl.gpsSub': '20,200 km', 'lbl.geo': 'Geostationary', 'lbl.geoSub': '35,786 km',
  'lbl.lightHour': '1 light-hour', 'lbl.lightDay': '1 light-day', 'lbl.kuiper': 'Kuiper belt', 'lbl.heliopause': 'Heliopause', 'lbl.heliopauseSub': '≈ 120 AU',
  'lbl.oort': 'Oort cloud', 'lbl.oortSub': '2,000 – 100,000 AU', 'lbl.radio': 'Radio bubble', 'lbl.radioSub': '100 light-years',
  'lbl.orion': 'Orion Arm', 'lbl.sun': 'Sun', 'lbl.earth': 'Earth', 'lbl.moon': 'Moon', 'lbl.sgra': 'Sgr A*', 'lbl.sgraSub': 'Galactic centre',
  'lbl.mw': 'Milky Way', 'lbl.here': 'Here', 'lbl.cmb': 'Cosmic microwave background', 'lbl.cmbSub': '380,000 years after the Big Bang',
  'lbl.pleiades': 'Pleiades', 'lbl.m42': 'Orion Nebula', 'lbl.alphacen': 'Alpha Centauri', 'lbl.barnard': 'Barnard’s Star',
  'lbl.proxima': 'Proxima Centauri', 'lbl.wolf359': 'Wolf 359', 'lbl.sirius': 'Sirius', 'lbl.procyon': 'Procyon', 'lbl.vega': 'Vega',
  'lbl.altair': 'Altair', 'lbl.arcturus': 'Arcturus', 'lbl.aldebaran': 'Aldebaran', 'lbl.betelgeuse': 'Betelgeuse', 'lbl.rigel': 'Rigel',
  'lbl.polaris': 'Polaris', 'lbl.deneb': 'Deneb', 'lbl.lmc': 'Large Magellanic Cloud', 'lbl.smc': 'Small Magellanic Cloud',
  'lbl.m31': 'Andromeda (M31)', 'lbl.m33': 'Triangulum (M33)', 'lbl.gattr': 'Great Attractor',
  'obj.iss': 'The International Space Station: 420 tonnes, 7.66 km/s, once around the Earth every 93 minutes. Continuously inhabited since November 2000.',
  'obj.gps': 'About 31 satellites in six orbital planes, 20,200 km up. Their atomic clocks must account for relativity: 38 microseconds per day.',
  'obj.geo': 'At 35,786 km one orbit takes exactly one day – the satellites appear to stand still in the sky. Weather and TV satellites live here.',
  'obj.lightHour': 'In one hour light travels 1.08 billion kilometres – roughly to the orbit of Saturn.',
  'obj.lightDay': 'One light-day: 25.9 billion kilometres, about 173 AU – already beyond the heliopause.',
  'obj.kuiper': 'Icy bodies beyond Neptune, 30 to 50 AU from the Sun. Pluto is the most famous – New Horizons flew past in 2015.',
  'obj.heliopause': 'Here the solar wind meets the interstellar medium – the Sun’s bubble ends. Voyager 1 crossed this boundary in August 2012.',
  'obj.oort': 'The edge of the solar system: trillions of icy bodies, home of the long-period comets. Never observed directly – interstellar space begins here.',
  'obj.radio': 'This is how far our first broadcasts from the 1920s have travelled. Some 10,000 stars lie inside this bubble – the rest of the Galaxy has never heard of us.',
  'obj.orion': 'The minor spiral arm that holds the Sun – between the Sagittarius and Perseus arms, about 10,000 light-years long.',
  'obj.proxima': 'Red dwarf, 4.24 light-years – the nearest star. With the planet Proxima b in the habitable zone.',
  'obj.alphacen': 'Rigil Kentaurus and Toliman: two Sun-like stars orbiting each other every 80 years. The third-brightest object in the night sky.',
  'obj.barnard': 'The star with the largest proper motion: 10.3 arcseconds per year. A red dwarf, 6 light-years away.',
  'obj.wolf359': 'One of the faintest known stars: a red dwarf with 9% of the Sun’s mass.',
  'obj.sirius': 'The brightest star in the night sky: 25 times the Sun’s luminosity, accompanied by the white dwarf Sirius B.',
  'obj.procyon': 'The eighth-brightest star, 11 light-years away – also with a white dwarf companion.',
  'obj.vega': 'Astronomy’s reference star (magnitude 0). 12,000 years ago Vega was the pole star.',
  'obj.altair': 'Spins so fast (once every 9 hours) that it is 20% wider at the equator than at the poles.',
  'obj.arcturus': 'A red giant 25 times the size of the Sun – the brightest star of the northern sky.',
  'obj.aldebaran': 'The red eye of the Bull: a red giant 44 times the size of the Sun.',
  'obj.betelgeuse': 'A red supergiant as large as Jupiter’s orbit. It will end as a supernova – sometime in the next 100,000 years.',
  'obj.rigel': 'A blue supergiant 120,000 times as luminous as the Sun, 860 light-years away.',
  'obj.polaris': 'The pole star: a supergiant 430 light-years away, almost exactly above Earth’s north pole.',
  'obj.deneb': 'One of the most luminous known stars: 200,000 Suns, about 2,600 light-years away.',
  'obj.pleiades': 'The Seven Sisters: about 1,000 young stars, 100 million years old, 444 light-years away.',
  'obj.m42': 'The nearest large star-forming region, 1,300 light-years away – visible as a smudge in Orion’s sword.',
  'obj.sgra': 'A black hole of 4 million solar masses, 26,000 light-years away. Imaged for the first time in 2022.',
  'obj.sunStar': 'From here: a yellow dwarf among billions. Its light is 8 minutes old when it reaches Earth.',
  'obj.mwHere': 'From here the Milky Way is a single point of light – one of some 2 trillion galaxies in the observable universe.',
  'obj.cmb': 'The oldest light: 380,000 years after the Big Bang the universe became transparent. The blotches – differences of a hundred-thousandth of a degree – are the seeds of all galaxies.',
  'obj.earthDot': 'The pale blue dot. Everything you know, on a single pixel.',
  'ms.moon.title': 'The <em>Moon</em>', 'ms.moon.label': 'Distance now',
  'ms.moon.txt': 'Our only natural satellite, 30 Earth diameters away. Twelve people have landed here – the last in 1972.',
  'ms.sun.title': 'The <em>Sun</em>', 'ms.sun.label': 'One astronomical unit',
  'ms.sun.txt': 'Its light is 8 minutes and 20 seconds old when it reaches us. 99.86% of the solar system’s mass sits in this one star.',
  'ms.neptune.title': '<em>Neptune</em>', 'ms.neptune.label': 'Distance now',
  'ms.neptune.txt': 'The outermost planet, 30 times farther from the Sun than Earth. From here the Sun is just a very bright star.',
  'ms.heliopause.title': '<em>Heliopause</em>', 'ms.heliopause.num': '≈ 120 AU', 'ms.heliopause.label': 'Edge of the solar wind',
  'ms.heliopause.txt': 'Here the solar wind meets the interstellar medium – the Sun’s bubble ends. Voyager 1 crossed this boundary in August 2012.',
  'ms.voyager1.title': '<em>Voyager 1</em>', 'ms.voyager1.label': 'Distance now',
  'ms.voyager1.txt': 'The most distant human-made object, launched in 1977, travelling at 17 km/s. A radio signal now takes over 23 hours to reach Earth.',
  'ms.oort.title': 'Oort <em>Cloud</em>', 'ms.oort.num': '2,000 – 100,000 AU', 'ms.oort.label': 'Extent · schematic',
  'ms.oort.txt': 'The edge of the solar system: trillions of icy bodies, home of the long-period comets. Never observed directly – interstellar space begins here.',
  'ms.proxima.title': 'Proxima <em>Centauri</em>', 'ms.proxima.num': '4.24 light-years', 'ms.proxima.label': 'The nearest star',
  'ms.proxima.txt': 'A red dwarf, too faint for the naked eye, with at least one planet. At Voyager’s speed the trip would take 75,000 years.',
  'ms.radio.title': '<em>Radio bubble</em>', 'ms.radio.num': '100 light-years', 'ms.radio.label': 'Reach of our signals',
  'ms.radio.txt': 'This is how far our first broadcasts from the 1920s have travelled. Some 10,000 stars lie inside this bubble – the rest of the Galaxy has never heard of us.',
  'ms.orion.title': 'Orion <em>Arm</em>', 'ms.orion.num': '10,000 light-years', 'ms.orion.label': 'Length of our spiral arm',
  'ms.orion.txt': 'The minor arm that holds the Sun – between the Sagittarius and Perseus arms. Almost every star you see with the naked eye belongs to it.',
  'ms.milkyway.title': '<em>Milky Way</em>', 'ms.milkyway.num': '100,000 light-years', 'ms.milkyway.label': 'Diameter · model',
  'ms.milkyway.txt': 'A barred spiral of 100 to 400 billion stars. The Sun takes 230 million years to circle Sagittarius A*, the black hole at the centre.',
  'ms.andromeda.title': '<em>Andromeda</em>', 'ms.andromeda.num': '2.5 million light-years', 'ms.andromeda.label': 'Distance',
  'ms.andromeda.txt': 'The nearest large galaxy and the most distant naked-eye object. In about 4.5 billion years it will merge with the Milky Way.',
  'ms.localgroup.title': 'Local <em>Group</em>', 'ms.localgroup.num': '≈ 80 galaxies', 'ms.localgroup.label': 'Milky Way, Andromeda & co.',
  'ms.localgroup.txt': 'Two large spirals, the Triangulum galaxy and dozens of dwarfs, bound by gravity – about 10 million light-years across.',
  'ms.virgo.title': 'Virgo <em>Cluster</em>', 'ms.virgo.num': '54 million light-years', 'ms.virgo.label': 'Distance',
  'ms.virgo.txt': 'Over 1,300 galaxies at the heart of our supercluster. Its mass slows the Local Group’s flight in the expanding universe.',
  'ms.edge2mrs.title': 'Edge of the <em>2MRS</em>', 'ms.edge2mrs.num': '43,506 galaxies', 'ms.edge2mrs.label': 'Real map up to here',
  'ms.edge2mrs.txt': 'This is how far the 2MASS Redshift Survey map reaches: every galaxy at its measured position. Everything farther out is schematic – a pattern, not a catalogue.',
  'ms.laniakea.title': '<em>Laniakea</em>', 'ms.laniakea.num': '520 million light-years', 'ms.laniakea.label': 'Diameter',
  'ms.laniakea.txt': 'Our supercluster: 100,000 galaxies all streaming towards the Great Attractor. Hawaiian for “immeasurable heaven”.',
  'ms.universe.title': 'Observable <em>Universe</em>', 'ms.universe.num': '46.5 billion light-years', 'ms.universe.label': 'Radius',
  'ms.universe.txt': 'The limit: the cosmic microwave background, light from 380,000 years after the Big Bang. No telescope can see beyond it – some 2 trillion galaxies lie inside this sphere.',
});
