import { registerStrings } from './i18n';

registerStrings('ui', {
  start: 'Los geht’s',
  close: 'Schliessen',
  back: 'Zurück',
  loading: 'Lade',
  error: 'Dieses Kapitel konnte nicht geladen werden. Bitte Seite neu laden.',
  sources: 'Quellen & Daten',
  menu: 'Menü',
  search: 'Suchen …',
  reset: 'Zurücksetzen',
  play: 'Abspielen',
  pause: 'Pause',
  now: 'Jetzt',
  more: 'Mehr',
  less: 'Weniger',
  offline: 'Keine Verbindung – Daten nicht verfügbar',
  lightyears: 'Lichtjahre',
  distance: 'Entfernung',
  lighttime: 'Lichtlaufzeit',
  magnitude: 'Helligkeit',
  luminosity: 'Leuchtkraft',
  temperature: 'Temperatur',
  mass: 'Masse',
  radius: 'Radius',
  type: 'Typ',
  constellation: 'Sternbild',
  dragHint: 'Ziehen zum Drehen · Scrollen zum Zoomen',
  flyHint: '<kbd>W</kbd><kbd>A</kbd><kbd>S</kbd><kbd>D</kbd> fliegen · Ziehen zum Umsehen · Scrollen für Tempo · <kbd>Shift</kbd> Turbo',
  tapHint: 'Objekt antippen für Details',
  sourceNote: 'Echte Daten: {src}',
}, {
  start: 'Let’s go',
  close: 'Close',
  back: 'Back',
  loading: 'Loading',
  error: 'This chapter could not be loaded. Please reload the page.',
  sources: 'Sources & data',
  menu: 'Menu',
  search: 'Search …',
  reset: 'Reset',
  play: 'Play',
  pause: 'Pause',
  now: 'Now',
  more: 'More',
  less: 'Less',
  offline: 'No connection – data unavailable',
  lightyears: 'light-years',
  distance: 'Distance',
  lighttime: 'Light travel time',
  magnitude: 'Brightness',
  luminosity: 'Luminosity',
  temperature: 'Temperature',
  mass: 'Mass',
  radius: 'Radius',
  type: 'Type',
  constellation: 'Constellation',
  dragHint: 'Drag to rotate · Scroll to zoom',
  flyHint: '<kbd>W</kbd><kbd>A</kbd><kbd>S</kbd><kbd>D</kbd> fly · Drag to look · Scroll for speed · <kbd>Shift</kbd> boost',
  tapHint: 'Tap an object for details',
  sourceNote: 'Real data: {src}',
});

// Chapter meta strings (titles are used in nav, intros and document.title). `<em>` = gold italic accent.
registerStrings('chapter', {
  'home.title': 'KOSMOS',
  'home.nav': 'Start',
  'home.subtitle': 'Eine Reise durch echte Daten des Universums',
  'stars.title': 'Sternen<em>flug</em>',
  'stars.nav': 'Sterne',
  'stars.subtitle': 'Flug durch 109’000 echte Sterne',
  'stars.blurb': 'Jeder Punkt ist ein vermessener Stern mit echter Position, Farbe und Helligkeit. Starte auf der Erde und fliege zu Sirius, Beteigeuze oder ans Ende des Katalogs.',
  'solarsystem.title': 'Sonnen<em>system</em>',
  'solarsystem.nav': 'Sonnensystem',
  'solarsystem.subtitle': 'Alle Planeten – jetzt gerade, an ihrem echten Ort',
  'solarsystem.blurb': 'Die Bahnen werden aus den Bahnelementen der NASA berechnet. Spule die Zeit vor und zurück und sieh, wo die Planeten heute, bei deiner Geburt oder in hundert Jahren stehen.',
  'exoplanets.title': 'Fremde <em>Welten</em>',
  'exoplanets.nav': 'Exoplaneten',
  'exoplanets.subtitle': 'Tausende bestätigte Planeten um andere Sterne',
  'exoplanets.blurb': 'Seit 1995 haben wir tausende Planeten um fremde Sterne entdeckt. Fliege zu ihnen, vergleiche sie mit der Erde und finde die, die in der bewohnbaren Zone kreisen.',
  'galaxies.title': 'Das kosmische <em>Netz</em>',
  'galaxies.nav': 'Galaxien',
  'galaxies.subtitle': '43’000 Galaxien mit echten Positionen',
  'galaxies.blurb': 'Die Milchstrasse ist eine von Billionen. Der 2MASS Redshift Survey hat 43’000 Galaxien in unserer Nachbarschaft vermessen: Fäden, Wände und Leerräume – das kosmische Netz.',
  'zoom.title': 'Kosmischer <em>Zoom</em>',
  'zoom.nav': 'Zoom',
  'zoom.subtitle': 'Von der Erde bis zum Rand des beobachtbaren Universums',
  'zoom.blurb': 'Zehnerpotenz für Zehnerpotenz hinaus: Mond, Planeten, die nächsten Sterne, die Milchstrasse, die Lokale Gruppe, Laniakea – bis zum Nachleuchten des Urknalls.',
  'timeline.title': 'Zeit<em>reise</em>',
  'timeline.nav': 'Zeit',
  'timeline.subtitle': '13,8 Milliarden Jahre – und was danach kommt',
  'timeline.blurb': 'Vom Urknall über die ersten Sterne bis zu dir. Und weiter: das Ende der Sonne, das Verschmelzen der Milchstrasse mit Andromeda und die ferne Zukunft des Kosmos.',
  'live.title': 'Gerade <em>jetzt</em>',
  'live.nav': 'Live',
  'live.subtitle': 'Was in diesem Moment im All passiert',
  'live.blurb': 'Wo ist die ISS? Wer ist gerade im All? Wann startet die nächste Rakete? Wie stark bläst der Sonnenwind? Live-Daten von NASA, NOAA und der Raumfahrt-Community.',
}, {
  'home.title': 'KOSMOS',
  'home.nav': 'Home',
  'home.subtitle': 'A journey through real data of the universe',
  'stars.title': 'Star <em>Flight</em>',
  'stars.nav': 'Stars',
  'stars.subtitle': 'Fly through 109,000 real stars',
  'stars.blurb': 'Every dot is a measured star with its true position, colour and brightness. Start on Earth and fly to Sirius, Betelgeuse or the edge of the catalogue.',
  'solarsystem.title': 'Solar <em>System</em>',
  'solarsystem.nav': 'Solar System',
  'solarsystem.subtitle': 'Every planet – right now, where it really is',
  'solarsystem.blurb': 'Orbits are computed from NASA orbital elements. Scrub time back and forth and see where the planets are today, on your birthday, or a century from now.',
  'exoplanets.title': 'Alien <em>Worlds</em>',
  'exoplanets.nav': 'Exoplanets',
  'exoplanets.subtitle': 'Thousands of confirmed planets around other stars',
  'exoplanets.blurb': 'Since 1995 we have found thousands of planets around other stars. Fly to them, compare them with Earth and find the ones orbiting in the habitable zone.',
  'galaxies.title': 'The Cosmic <em>Web</em>',
  'galaxies.nav': 'Galaxies',
  'galaxies.subtitle': '43,000 galaxies at their real positions',
  'galaxies.blurb': 'The Milky Way is one of trillions. The 2MASS Redshift Survey mapped 43,000 galaxies in our neighbourhood: filaments, walls and voids – the cosmic web.',
  'zoom.title': 'Cosmic <em>Zoom</em>',
  'zoom.nav': 'Zoom',
  'zoom.subtitle': 'From Earth to the edge of the observable universe',
  'zoom.blurb': 'Outwards, power of ten by power of ten: the Moon, the planets, the nearest stars, the Milky Way, the Local Group, Laniakea – all the way to the afterglow of the Big Bang.',
  'timeline.title': 'Time <em>Travel</em>',
  'timeline.nav': 'Time',
  'timeline.subtitle': '13.8 billion years – and what comes after',
  'timeline.blurb': 'From the Big Bang via the first stars to you. And beyond: the death of the Sun, the merger of the Milky Way and Andromeda, and the far future of the cosmos.',
  'live.title': 'Right <em>Now</em>',
  'live.nav': 'Live',
  'live.subtitle': 'What is happening in space this very moment',
  'live.blurb': 'Where is the ISS? Who is in space right now? When is the next launch? How strong is the solar wind? Live data from NASA, NOAA and the spaceflight community.',
});

registerStrings('credits', {
  title: 'Quellen & Daten',
  intro: 'Alle Positionen, Helligkeiten und Entfernungen stammen aus öffentlichen wissenschaftlichen Katalogen. Live-Daten werden direkt im Browser abgerufen.',
  catalogs: 'Kataloge',
  live: 'Live-Daten',
  tech: 'Technik',
  hyg: 'HYG Stellar Database v4.1 (Hipparcos, Yale Bright Star, Gliese) – David Nash, CC BY-SA 4.0',
  twomrs: '2MASS Redshift Survey (2MRS) – Huchra et al. 2012, ApJS 199, 26',
  oec: 'Open Exoplanet Catalogue – Hanno Rein et al., MIT-Lizenz',
  openngc: 'OpenNGC – Mattia Verga, CC BY-SA 4.0',
  stellarium: 'Sternbildlinien: Stellarium (modern sky culture), CC BY-SA 4.0',
  jpl: 'Bahnelemente der Planeten: NASA/JPL «Keplerian Elements for Approximate Positions of the Major Planets»',
  textures: 'Erd- und Mondtexturen: NASA Blue Marble / three.js (MIT)',
  iss: 'ISS-Position: wheretheiss.at (NORAD/TLE)',
  ll2: 'Starts & Astronauten: The Space Devs – Launch Library 2',
  noaa: 'Weltraumwetter: NOAA Space Weather Prediction Center',
  nasa: 'Asteroiden & Bild des Tages: NASA Open APIs',
  sdo: 'Sonnenbilder: NASA Solar Dynamics Observatory',
  sen: 'Live-Video der Erde: Sen (YouTube)',
  three: 'Rendering: three.js · Build: Vite · Schrift: Manrope, Instrument Serif',
  madeWith: 'Gebaut mit Neugier.',
}, {
  title: 'Sources & data',
  intro: 'All positions, brightnesses and distances come from public scientific catalogues. Live data is fetched directly in your browser.',
  catalogs: 'Catalogues',
  live: 'Live data',
  tech: 'Technology',
  hyg: 'HYG Stellar Database v4.1 (Hipparcos, Yale Bright Star, Gliese) – David Nash, CC BY-SA 4.0',
  twomrs: '2MASS Redshift Survey (2MRS) – Huchra et al. 2012, ApJS 199, 26',
  oec: 'Open Exoplanet Catalogue – Hanno Rein et al., MIT license',
  openngc: 'OpenNGC – Mattia Verga, CC BY-SA 4.0',
  stellarium: 'Constellation lines: Stellarium (modern sky culture), CC BY-SA 4.0',
  jpl: 'Planetary orbital elements: NASA/JPL "Keplerian Elements for Approximate Positions of the Major Planets"',
  textures: 'Earth and Moon textures: NASA Blue Marble / three.js (MIT)',
  iss: 'ISS position: wheretheiss.at (NORAD/TLE)',
  ll2: 'Launches & astronauts: The Space Devs – Launch Library 2',
  noaa: 'Space weather: NOAA Space Weather Prediction Center',
  nasa: 'Asteroids & picture of the day: NASA Open APIs',
  sdo: 'Solar images: NASA Solar Dynamics Observatory',
  sen: 'Live video of Earth: Sen (YouTube)',
  three: 'Rendering: three.js · Build: Vite · Type: Manrope, Instrument Serif',
  madeWith: 'Built with curiosity.',
});
