import { registerStrings } from '../../core/i18n';

/** Exoplanets chapter strings – German first, English second. Keys are used as t('exoplanets.<key>'). */
registerStrings('exoplanets', {
  kicker: 'Kapitel 3 · KOSMOS',
  hint: 'Ziehen zum Drehen · Scrollen zum Zoomen · Stern anklicken für das System · Doppelklick: Freiflug',
  hintTouch: 'Ziehen zum Drehen · Zwei Finger zum Zoomen · Stern antippen',
  source: 'Daten: Open Exoplanet Catalogue, Stand {updated}',
  sourceShort: 'Daten: Open Exoplanet Catalogue',
  sourceStars: 'Hintergrund: HYG v4.1 / Hipparcos',

  // tabs / modes
  tabMap: 'Karte',
  tabCharts: 'Diagramm',
  freeflight: 'Freiflug',
  orbit: 'Orbit',
  toSun: 'Zur Sonne',
  reset: 'Zurücksetzen',
  filters: 'Filter',
  sun: 'Sonne',
  ly: 'Lj',
  ring: '{n} Lichtjahre',

  // filters
  method: 'Entdeckungsmethode',
  sizeClass: 'Grössenklasse',
  sizeNote: 'nach Radius, sonst nach Masse',
  hzOnly: 'Nur bewohnbare Zone',
  maxDist: 'Max. Entfernung',
  year: 'Entdeckungsjahr',
  known: 'Bekannte Planeten',
  play: 'Entdeckungen abspielen',
  pause: 'Pause',
  all: 'alle',
  shown: '{n} von {total} Planeten · {hosts} Sterne',
  search: 'Stern oder Planet suchen …',
  searchLabel: 'Suche',
  noResults: 'Nichts gefunden',
  notFound: 'Nicht gefunden: {q}',
  noPosition: 'Für {host} ist keine Entfernung bekannt – kein Ort auf der Karte.',
  planetsN: '{n} Planeten',
  planet1: '1 Planet',

  'm.transit': 'Transit',
  'm.RV': 'Radialgeschwindigkeit',
  'm.imaging': 'Direkte Abbildung',
  'm.microlensing': 'Mikrolinse',
  'm.timing': 'Timing',
  'm.astrometry': 'Astrometrie',
  'm.other': 'andere',
  'mShort.transit': 'Transit',
  'mShort.RV': 'Radialgeschw.',
  'mShort.imaging': 'Abbildung',
  'mShort.microlensing': 'Mikrolinse',
  'mShort.timing': 'Timing',
  'mShort.astrometry': 'Astrometrie',
  'mShort.other': 'andere',

  's.earth': 'Erdähnlich',
  's.super': 'Supererde',
  's.neptune': 'Neptunartig',
  's.jupiter': 'Jupiterartig',
  's.unknown': 'unbekannt',
  'sRange.earth': '< 1,6 R⊕',
  'sRange.super': '1,6–2,5 R⊕',
  'sRange.neptune': '2,5–6 R⊕',
  'sRange.jupiter': '> 6 R⊕',
  'sRange.unknown': 'kein Radius',

  // info card
  system: 'Planetensystem',
  distance: 'Entfernung',
  lightSentence: 'Das Licht, das wir heute sehen, verliess den Stern vor {t}.',
  lightSentenceNow: 'Das Licht ist {t} unterwegs.',
  star: 'Stern',
  teff: 'Oberflächentemperatur',
  stMass: 'Masse',
  stRadius: 'Radius',
  suns: '× Sonne',
  unknownVal: 'unbekannt',
  binary: 'Doppelstern',
  diagram: 'Das System',
  diagramNote: 'Abstände logarithmisch · Planetengrösse ∝ log Radius',
  hzBand: 'Bewohnbare Zone',
  earthTick: 'Erde-Äquivalent',
  au: 'AE',
  colPlanet: 'Planet',
  colMass: 'Masse',
  colRadius: 'Radius',
  colPeriod: 'Umlaufzeit',
  colSma: 'Abstand',
  colTemp: 'Temp.',
  colYear: 'Entdeckt',
  colMethod: 'Methode',
  inHz: 'bewohnbare Zone',
  xEarth: '× Erde',
  xJupiter: '× Jupiter',
  days: 'Tage',
  day1: 'Tag',
  smaDerived: '* aus Umlaufzeit und Sternmasse berechnet (3. Kepler-Gesetz)',
  radiusEstimated: '° Radius aus der Masse geschätzt',
  flyTo: 'Hinfliegen',
  showChart: 'Im Diagramm',
  hostNoStar: 'Frei fliegender Planet ohne Stern – oder ohne bekannte Sterndaten.',

  // stats
  stTotal: 'Bestätigte Planeten',
  stHz: 'in der bewohnbaren Zone',
  stNearest: 'Nächster',
  stSmallest: 'Kleinster',
  stLargest: 'Grösster',
  stEarliest: 'Erste Entdeckung',
  stMedian: 'Mittlere Entfernung',
  stMedianSub: 'Median aller Planeten',
  stHosts: 'Sterne mit Planeten',
  stMulti: 'Systeme mit mehreren Planeten',
  radiiEarth: 'Erdradien',
  lyAway: 'Lichtjahre entfernt',

  // charts
  chartsTitle: 'Die Vermessung der <em>fremden Welten</em>',
  chartsSub: 'Was wir bisher gefunden haben – und wie.',
  scatterTitle: 'Umlaufzeit und Masse',
  scatterTitleR: 'Umlaufzeit und Radius',
  scatterSub: 'Jeder Punkt ein Planet · Farbe und Form = Entdeckungsmethode · Klick öffnet das System',
  axisPeriod: 'Umlaufzeit (Tage)',
  axisMass: 'Masse (Erdmassen)',
  axisRadius: 'Radius (Erdradien)',
  toggleMass: 'Masse',
  toggleRadius: 'Radius',
  refEarth: 'Erde',
  refJupiter: 'Jupiter',
  refNeptune: 'Neptun',
  refMercury: 'Merkur',
  legendHint: 'Methode anklicken zum Hervorheben',
  clickForSystem: 'Klicken für das System',
  scatterCount: '{n} Planeten mit bekannter Umlaufzeit und {q}',
  qMass: 'Masse',
  qRadius: 'Radius',
  yearTitle: 'Entdeckungen pro Jahr',
  yearSub: 'Bestätigte Planeten nach Entdeckungsjahr · die grossen Sprünge sind Kepler-Auswertungen',
  discoveries: 'Entdeckungen',
  cumulative: 'insgesamt',
  'ms.1995': '51 Peg b – erster Planet um einen sonnenähnlichen Stern',
  'ms.2009': 'Weltraumteleskop Kepler startet',
  'ms.2014': 'Kepler: 715 Planeten auf einen Schlag bestätigt',
  'ms.2016': 'Kepler: 1284 Planeten validiert',
  'ms.2018': 'TESS startet',
  'ms.2022': '5000. Exoplanet',
  'msShort.1995': '51 Peg b',
  'msShort.2009': 'Kepler',
  'msShort.2014': '715 bestätigt',
  'msShort.2016': '1284 validiert',
  'msShort.2018': 'TESS',
  'msShort.2022': '5000.',
  shareTitle: 'Wie wir sie finden',
  shareSub: 'Anteil der Entdeckungsmethoden',
  sizeTitle: 'Wie gross sie sind',
  sizeSub: 'Grössenklassen nach Radius (sonst nach Masse)',
  tableView: 'Tabelle',
  chartView: 'Diagramm',
  colShare: 'Anteil',
  colCount: 'Anzahl',
  colClass: 'Klasse',
}, {
  kicker: 'Chapter 3 · KOSMOS',
  hint: 'Drag to rotate · Scroll to zoom · Click a star for its system · Double-click: free flight',
  hintTouch: 'Drag to rotate · Pinch to zoom · Tap a star',
  source: 'Data: Open Exoplanet Catalogue, as of {updated}',
  sourceShort: 'Data: Open Exoplanet Catalogue',
  sourceStars: 'Background: HYG v4.1 / Hipparcos',

  tabMap: 'Map',
  tabCharts: 'Charts',
  freeflight: 'Free flight',
  orbit: 'Orbit',
  toSun: 'To the Sun',
  reset: 'Reset',
  filters: 'Filters',
  sun: 'Sun',
  ly: 'ly',
  ring: '{n} light-years',

  method: 'Discovery method',
  sizeClass: 'Size class',
  sizeNote: 'by radius, else by mass',
  hzOnly: 'Habitable zone only',
  maxDist: 'Max. distance',
  year: 'Year of discovery',
  known: 'Known planets',
  play: 'Play discoveries',
  pause: 'Pause',
  all: 'all',
  shown: '{n} of {total} planets · {hosts} stars',
  search: 'Search star or planet …',
  searchLabel: 'Search',
  noResults: 'Nothing found',
  notFound: 'Not found: {q}',
  noPosition: 'No distance is known for {host} – it has no place on the map.',
  planetsN: '{n} planets',
  planet1: '1 planet',

  'm.transit': 'Transit',
  'm.RV': 'Radial velocity',
  'm.imaging': 'Direct imaging',
  'm.microlensing': 'Microlensing',
  'm.timing': 'Timing',
  'm.astrometry': 'Astrometry',
  'm.other': 'other',
  'mShort.transit': 'Transit',
  'mShort.RV': 'Radial vel.',
  'mShort.imaging': 'Imaging',
  'mShort.microlensing': 'Microlensing',
  'mShort.timing': 'Timing',
  'mShort.astrometry': 'Astrometry',
  'mShort.other': 'other',

  's.earth': 'Earth-like',
  's.super': 'Super-Earth',
  's.neptune': 'Neptune-like',
  's.jupiter': 'Jupiter-like',
  's.unknown': 'unknown',
  'sRange.earth': '< 1.6 R⊕',
  'sRange.super': '1.6–2.5 R⊕',
  'sRange.neptune': '2.5–6 R⊕',
  'sRange.jupiter': '> 6 R⊕',
  'sRange.unknown': 'no radius',

  system: 'Planetary system',
  distance: 'Distance',
  lightSentence: 'The light we see today left the star {t} ago.',
  lightSentenceNow: 'Its light travels {t} to reach us.',
  star: 'Star',
  teff: 'Surface temperature',
  stMass: 'Mass',
  stRadius: 'Radius',
  suns: '× Sun',
  unknownVal: 'unknown',
  binary: 'binary star',
  diagram: 'The system',
  diagramNote: 'Log distances · planet size ∝ log radius',
  hzBand: 'Habitable zone',
  earthTick: 'Earth equivalent',
  au: 'AU',
  colPlanet: 'Planet',
  colMass: 'Mass',
  colRadius: 'Radius',
  colPeriod: 'Period',
  colSma: 'Distance',
  colTemp: 'Temp.',
  colYear: 'Found',
  colMethod: 'Method',
  inHz: 'habitable zone',
  xEarth: '× Earth',
  xJupiter: '× Jupiter',
  days: 'days',
  day1: 'day',
  smaDerived: '* derived from period and stellar mass (Kepler’s third law)',
  radiusEstimated: '° radius estimated from mass',
  flyTo: 'Fly there',
  showChart: 'In the chart',
  hostNoStar: 'Free-floating planet without a star – or without known stellar data.',

  stTotal: 'Confirmed planets',
  stHz: 'in the habitable zone',
  stNearest: 'Nearest',
  stSmallest: 'Smallest',
  stLargest: 'Largest',
  stEarliest: 'First discovery',
  stMedian: 'Median distance',
  stMedianSub: 'median of all planets',
  stHosts: 'Stars with planets',
  stMulti: 'Multi-planet systems',
  radiiEarth: 'Earth radii',
  lyAway: 'light-years away',

  chartsTitle: 'Surveying the <em>alien worlds</em>',
  chartsSub: 'What we have found so far – and how.',
  scatterTitle: 'Orbital period and mass',
  scatterTitleR: 'Orbital period and radius',
  scatterSub: 'Every dot is a planet · colour and shape = discovery method · click opens the system',
  axisPeriod: 'Orbital period (days)',
  axisMass: 'Mass (Earth masses)',
  axisRadius: 'Radius (Earth radii)',
  toggleMass: 'Mass',
  toggleRadius: 'Radius',
  refEarth: 'Earth',
  refJupiter: 'Jupiter',
  refNeptune: 'Neptune',
  refMercury: 'Mercury',
  legendHint: 'Click a method to highlight it',
  clickForSystem: 'Click for the system',
  scatterCount: '{n} planets with known period and {q}',
  qMass: 'mass',
  qRadius: 'radius',
  yearTitle: 'Discoveries per year',
  yearSub: 'Confirmed planets by year of discovery · the big jumps are Kepler data releases',
  discoveries: 'discoveries',
  cumulative: 'in total',
  'ms.1995': '51 Peg b – first planet around a Sun-like star',
  'ms.2009': 'Kepler space telescope launches',
  'ms.2014': 'Kepler: 715 planets confirmed at once',
  'ms.2016': 'Kepler: 1,284 planets validated',
  'ms.2018': 'TESS launches',
  'ms.2022': '5,000th exoplanet',
  'msShort.1995': '51 Peg b',
  'msShort.2009': 'Kepler',
  'msShort.2014': '715 confirmed',
  'msShort.2016': '1,284 validated',
  'msShort.2018': 'TESS',
  'msShort.2022': '5,000th',
  shareTitle: 'How we find them',
  shareSub: 'Share of discovery methods',
  sizeTitle: 'How big they are',
  sizeSub: 'Size classes by radius (else by mass)',
  tableView: 'Table',
  chartView: 'Chart',
  colShare: 'Share',
  colCount: 'Count',
  colClass: 'Class',
});
